import test from 'node:test';
import http from 'node:http';
import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createAPI} from '../server/service.mjs';
import {createServer} from '../server/main.mjs';
import {starterCharacters as characters,starterStory} from '../content/seed.mjs';
const stories=[starterStory];
test('isolated community: ownership, immutable versions, reconciliation and moderation',async t=>{
 const dir=await mkdtemp(join(tmpdir(),'ea3-community-test-')),api=await createAPI({dataDir:dir,hooks:{afterPublication(result,req,res){if(result.operationId==='uncertain-operation-01')res.destroy();}}}),server=createServer({port:0,apiHandler:api}),listening=await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve)),origin=`http://127.0.0.1:${server.address().port}`;
 const call=async(path,{method='GET',body,token,headers={}}={})=>{const r=await fetch(origin+path,{method,headers:{...(body!==undefined?{'Content-Type':'application/json'}:{}),...(token?{Authorization:'Bearer '+token}:{}),...headers},body:body!==undefined?JSON.stringify(body):undefined});return {status:r.status,headers:r.headers,data:await r.json()};};
 try{
  let alice,bob,moderator,v1,v2,v3,report;
  await t.test('anonymous local community read; privileged routes require authentication',async()=>{assert.equal((await call('/api/public/items')).status,200);assert.equal((await call('/api/admin/reports')).status,401);});
  await t.test('registration ignores privilege injection; secure password hashing and opaque session',async()=>{
    alice=(await call('/api/register',{method:'POST',body:{username:'test_alice',password:'Synthetic-test-password-alice',role:'admin',tokenMode:true}})).data;
    bob=(await call('/api/register',{method:'POST',body:{username:'test_bob',password:'Synthetic-test-password-bob',tokenMode:true}})).data;
    moderator=(await call('/api/register',{method:'POST',body:{username:'test_moderator',password:'Synthetic-test-password-mod',tokenMode:true}})).data;
    assert.equal(alice.user.role,'player');assert.match(alice.token,/^[a-f0-9]{64}$/);const row=api.context.db.prepare('SELECT * FROM users WHERE id=?').get(alice.user.id);assert.notEqual(row.hash,'Synthetic-test-password-alice');assert.equal(row.hash.length,128);assert.ok(row.salt);api.context.db.prepare("UPDATE users SET role='moderator' WHERE id=?").run(moderator.user.id);
  });
  const bodyFor=(operationId,extra={})=>({operationId,content:{...structuredClone(characters[0]),creator:'Original credited author'},characters:[],assets:[],...extra});
  await t.test('publish retains creator separately from uploader and returns exact public identity',async()=>{const r=await call('/api/publish',{method:'POST',token:alice.token,body:bodyFor('publish-version-01')});assert.equal(r.status,201,JSON.stringify(r.data));v1=r.data;const d=await call('/api/versions/'+v1.versionId);assert.equal(d.data.summary.creator,'Original credited author');assert.equal(d.data.summary.uploader,'test_alice');assert.equal(d.data.content.public.versionId,v1.versionId);});
  await t.test('same operation is idempotent; altered request under same ID is rejected',async()=>{const r=await call('/api/publish',{method:'POST',token:alice.token,body:bodyFor('publish-version-01')});assert.equal(r.status,200);assert.equal(r.data.versionId,v1.versionId);assert.equal(r.data.reconciled,true);const b=bodyFor('publish-version-01');b.content.name+=' altered';assert.equal((await call('/api/publish',{method:'POST',token:alice.token,body:b})).status,409);});
  await t.test('a different uploader cannot update the same item',async()=>{assert.equal((await call('/api/publish',{method:'POST',token:bob.token,body:bodyFor('attack-update-01',{itemId:v1.itemId})})).status,403);});
  await t.test('only immediately previous version is hidden; older version attribution is immutable',async()=>{
    const b=bodyFor('publish-version-02',{itemId:v1.itemId});b.content.creator='Revised credited author';v2=(await call('/api/publish',{method:'POST',token:alice.token,body:b})).data;
    v3=(await call('/api/publish',{method:'POST',token:alice.token,body:bodyFor('publish-version-03',{itemId:v1.itemId,hidePrevious:true})})).data;
    assert.equal(v3.hiddenPrevious,v2.versionId);assert.equal((await call('/api/versions/'+v2.versionId)).status,404);assert.equal((await call('/api/versions/'+v2.versionId,{token:alice.token})).status,200);const old=await call('/api/versions/'+v1.versionId);assert.equal(old.status,200);assert.equal(old.data.summary.creator,'Original credited author');
  });
  await t.test('exact-version feedback works independently of a downloaded local copy',async()=>{assert.equal((await call('/api/ratings',{method:'PUT',token:bob.token,body:{versionId:v1.versionId,score:4,comment:'Synthetic local-download feedback'}})).status,200);const r=await call('/api/reports',{method:'POST',token:bob.token,body:{versionId:v1.versionId,reason:'classification',details:'Synthetic moderation fixture: review this original version.',contact:'reporter@example.invalid'}});assert.equal(r.status,201);report=r.data;});
  await t.test('moderator sees actual reported JSON, image, contact, original hash and uploader',async()=>{const r=await call('/api/admin/reports/'+report.id,{token:moderator.token});assert.equal(r.status,200,JSON.stringify(r.data));assert.equal(r.data.report.version_id,v1.versionId);assert.equal(r.data.report.contact,'reporter@example.invalid');assert.equal(r.data.reportedContent.name,characters[0].name);assert.equal(r.data.snapshotMatches,true);assert.ok(r.data.reportedContent.image);assert.equal(r.data.uploader.username,'test_alice');assert.equal((await call('/api/admin/reports/'+report.id,{token:bob.token})).status,403);});
  await t.test('corrective reclassification preserves original report snapshot; reply draft is not sent',async()=>{let r=await call('/api/admin/reports/'+report.id,{method:'POST',token:moderator.token,body:{action:'reclassify',rating:'mature',note:'Synthetic classification correction.'}});assert.equal(r.data.reportedContent.rating,'sfw');assert.equal(r.data.version.content.rating,'mature');assert.equal(r.data.snapshotMatches,true);r=await call('/api/admin/reports/'+report.id,{method:'POST',token:moderator.token,body:{action:'reply-draft',note:'We reviewed the exact version and corrected its classification.'}});assert.equal(r.data.report.reply_sent_at,null);assert.ok(r.data.report.reply_draft);assert.equal((await call('/api/admin/reports/'+report.id,{method:'POST',token:moderator.token,body:{action:'reply-sent',note:'Opened a mail composer only.'}})).status,422);});
  await t.test('moderation lock blocks further versions and actions leave resolution history',async()=>{await call('/api/admin/reports/'+report.id,{method:'POST',token:moderator.token,body:{action:'lock',note:'Synthetic lock pending uploader review.'}});assert.equal((await call('/api/publish',{method:'POST',token:alice.token,body:bodyFor('publish-locked-04',{itemId:v1.itemId})})).status,423);const r=await call('/api/admin/reports/'+report.id,{method:'POST',token:moderator.token,body:{action:'resolve',note:'Classification corrected; uploader changes locked for review.'}});assert.equal(r.data.report.state,'resolved');assert.ok(r.data.history.some(a=>a.action==='lock'));});
  await t.test('dropped response after committed publish is reconciled without duplicate version',async()=>{
    await assert.rejects(()=>call('/api/publish',{method:'POST',token:alice.token,body:bodyFor('uncertain-operation-01')}));const receipt=await call('/api/operations/uncertain-operation-01',{token:alice.token});assert.equal(receipt.status,200);assert.equal(receipt.data.number,1);assert.equal(api.context.db.prepare('SELECT COUNT(*) AS n FROM versions WHERE item_id=?').get(receipt.data.itemId).n,1);assert.equal((await call('/api/operations/uncertain-operation-01',{token:bob.token})).status,404);
  });
  await t.test('story publication includes cast; missing dependency is rejected atomically',async()=>{const story=stories[0],base={operationId:'story-publish-01',content:story,assets:[]};assert.equal((await call('/api/publish',{method:'POST',token:alice.token,body:base})).status,422);const all=[...(story.cast||[]),...(story.backgroundCast||[])];base.characters=characters.filter(c=>all.includes(c.id));const r=await call('/api/publish',{method:'POST',token:alice.token,body:base});assert.equal(r.status,201,JSON.stringify(r.data));assert.equal((await call('/api/versions/'+r.data.versionId)).data.characters.length,all.length);});
  await t.test('unsafe assets, prototype input, malformed schemas and out-of-range ratings are rejected',async()=>{let b=bodyFor('unsafe-image-01');b.content.image='https://tracking.example.invalid/pixel';assert.equal((await call('/api/publish',{method:'POST',token:alice.token,body:b})).status,422);b=bodyFor('bad-schema-01');b.content.name=42;assert.equal((await call('/api/publish',{method:'POST',token:alice.token,body:b})).status,422);assert.equal((await call('/api/ratings',{method:'PUT',token:bob.token,body:{versionId:v3.versionId,score:7}})).status,422);});
  await t.test('cross-site writes, spoofed Host and private server files are denied',async()=>{assert.equal((await call('/api/logout',{method:'POST',body:{},headers:{Origin:'https://evil.example'}})).status,403);const spoofed=await new Promise((resolve,reject)=>{http.get(origin+'/api/health',{headers:{Host:'attacker.example'}},r=>{r.resume();r.on('end',()=>resolve(r.statusCode));}).on('error',reject);});assert.equal(spoofed,403);assert.equal((await call('/server/db.mjs')).status,404);assert.equal((await call('/.runtime/community.sqlite')).status,404);const r=await fetch(origin+'/operator.html');assert.match(r.headers.get('content-security-policy'),/frame-ancestors 'none'/);});
  await t.test('restricted accounts cannot publish, rate or evade restriction through existing session',async()=>{await call('/api/admin/reports/'+report.id,{method:'POST',token:moderator.token,body:{action:'restrict-uploader',note:'Synthetic restriction for acceptance testing only.'}});assert.equal((await call('/api/publish',{method:'POST',token:alice.token,body:bodyFor('restricted-new-01')})).status,403);assert.equal((await call('/api/login',{method:'POST',body:{username:'test_alice',password:'Synthetic-test-password-alice'}})).status,403);});
 }finally{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));api.close();await rm(dir,{recursive:true,force:true});}
});
