import test from 'node:test';import assert from 'node:assert/strict';
import {CommunityClient,preparePublication,importPublication} from '../app/community.mjs';
import {MemoryRepository} from './support/memory-repository.mjs';
import {starterStory,starterCharacters} from '../content/seed.mjs';
const summary={itemId:'publication',versionId:'v1',number:1,ownerId:'author',uploader:'tester'};
async function setup(){const repo=new MemoryRepository();for(const c of starterCharacters)await repo.putContent(c);await repo.putContent(starterStory);return repo;}
test('publication preparation includes complete cast but no local metadata',async()=>{const repo=await setup(),c=await repo.getContent('story',starterStory.id);const b=await preparePublication(repo,c);assert.equal(b.characters.length,3);assert.equal(b.content.contentRevision,undefined);assert.equal(b.content.public,undefined);assert.equal((await repo.getContent('story',c.id)).contentRevision,c.contentRevision);});
test('download imports dependencies atomically and remaps colliding character references',async()=>{const repo=await setup(),bundle={content:structuredClone(starterStory),characters:structuredClone(starterCharacters),summary};bundle.content.initial.relationships={rhea:2};const r=await importPublication(repo,bundle);assert.notEqual(r.localId,starterStory.id);const story=await repo.getContent('story',r.localId);assert.notEqual(story.cast[0],'rhea');assert.equal(story.initial.relationships[story.cast[0]],2);assert.equal(story.public.versionId,'v1');assert.equal((await repo.getContent('character','rhea')).name,'Rhea Ashford');assert.equal((await importPublication(repo,bundle)).duplicate,true);});
test('invalid dependency or unsafe images leave local library unchanged',async()=>{const repo=await setup(),before=await repo.snapshot();await assert.rejects(importPublication(repo,{content:starterStory,characters:[],summary}),/dependency/);const c=structuredClone(starterCharacters[0]);c.image='https://tracking.example.invalid/x';await assert.rejects(importPublication(repo,{content:c,summary}),/unsafe/);assert.deepEqual(await repo.snapshot(),before);});
test('a failed import transaction does not leave detached characters or images',async()=>{const repo=await setup(),before=await repo.snapshot();repo.failNext=new Error('Quota full');await assert.rejects(importPublication(repo,{content:starterStory,characters:starterCharacters,summary}),/Quota/);assert.deepEqual(await repo.snapshot(),before);});
test('dropped publish response is reconciled exactly once without republishing',async()=>{const repo=await setup(),c=await repo.getContent('character','rhea');let attempts=0;const client=new CommunityClient({transport:async(path)=>{if(path==='/api/publish'){attempts++;throw new Error('Connection dropped');}assert.ok(path.startsWith('/api/operations/'));return new Response(JSON.stringify(summary));}});const r=await client.publish(repo,c);assert.equal(attempts,1);assert.equal(r.localLinked,true);assert.equal((await repo.getContent('character','rhea')).public.versionId,'v1');assert.equal((await repo.all('jobs')).length,0);});
test('unknown publication result retains receipt request and never retries with a new ID',async()=>{const repo=await setup(),c=await repo.getContent('character','rhea'),client=new CommunityClient({transport:async()=>{throw new Error('Disconnected');}});await assert.rejects(client.publish(repo,c),/Disconnected/);const jobs=await repo.all('jobs');assert.equal(jobs.length,1);assert.equal(jobs[0].state,'failed-or-unknown');assert.ok(jobs[0].payload.operationId);});
test('newer local content survives a successful remote publication',async()=>{const repo=await setup(),c=await repo.getContent('character','rhea');const client=new CommunityClient({transport:async()=>{await repo.putContent({...c,name:'Updated local draft'},{expectedRevision:c.contentRevision});return new Response(JSON.stringify(summary));}});const r=await client.publish(repo,c);assert.equal(r.localLinked,false);assert.equal((await repo.getContent('character','rhea')).name,'Updated local draft');assert.equal((await repo.all('jobs'))[0].state,'committed');});
