import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createServer} from '../server/main.mjs';
import {GenerationService,FileJournal} from '../server/generation.mjs';
import {normalizedResponse,readSSE} from '../app/providers/stream.mjs';
import {HttpProvider} from '../app/providers/http.mjs';
import {narrativePrompt,imagePrompt,parseDraft} from '../app/providers/prompts.mjs';
const req={schema:'ea3/narration/1',action:{kind:'continue',id:'request-test-12345'},story:{title:'A fixture',initiative:'npc'},player:{name:'Rowan',rating:'sfw'},scene:{text:'At the inn',authored:'Rhea opens a map.'},state:{resources:{gold:3},memory:[{text:'A public fact',rating:'sfw'},{text:'A private mature fact',rating:'mature'}]},recent:[],continueWithoutPlayerDecision:true};
function stream(text,width=7){const bytes=new TextEncoder().encode(text);let i=0;return new ReadableStream({pull(controller){if(i>=bytes.length)return controller.close();controller.enqueue(bytes.slice(i,i+width));i+=width;}});}
function memoryJournal(){const data=new Map();return {get:async(o,id)=>data.get(o+'|'+id),put:async(o,r)=>data.set(o+'|'+r.id,structuredClone(r))};}
async function service(t,fetcher,env={}){
  const generation=new GenerationService({env:{TEXT_ENDPOINT:'http://upstream.invalid/v1/chat/completions',TEXT_API_KEY:'server-secret-fixture',...env},journal:memoryJournal(),fetcher});
  const server=createServer({apiHandler:(req,res,url)=>generation.handle(req,res,url)});await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>{generation.close();server.closeAllConnections();server.close();});
  return {url:`http://127.0.0.1:${server.address().port}`,generation};
}
test('SSE parser preserves UTF-8, split boundaries and CRLF',async()=>{const events=[];await readSSE(stream('event: chunk\r\ndata: {"text":"héllo 🌍"}\r\n\r\nevent: result\ndata: {"text":"done"}\n\n',1),e=>events.push(e));assert.equal(JSON.parse(events[0].data).text,'héllo 🌍');assert.equal(events[1].type,'result');});
test('normalized SSE refuses a stream without a completed result',async()=>{await assert.rejects(normalizedResponse(new Response(stream('event: chunk\ndata: {"text":"partial"}\n\n'),{headers:{'Content-Type':'text/event-stream'}})),/without a completed result/);});
test('normalized SSE refuses duplicate terminal results',async()=>{await assert.rejects(normalizedResponse(new Response(stream('event: result\ndata: {"text":"one"}\n\nevent: result\ndata: {"text":"two"}\n\n'),{headers:{'Content-Type':'text/event-stream'}})),/Duplicate/);});
test('provider context filters mature memories without changing saved state',()=>{const p=narrativePrompt(req);assert.ok(p.user.includes('A public fact'));assert.ok(!p.user.includes('A private mature fact'));assert.equal(req.state.memory.length,2);assert.ok(p.system.includes('CONTINUE'));});
test('history budgeting is disclosed and does not truncate authored state',()=>{const r={...req,recent:Array.from({length:30},()=>({text:'a'.repeat(1000)}))};const p=narrativePrompt(r,{budget:5000});assert.ok(p.context.omittedEarlierTurns>0);assert.equal(r.recent.length,30);assert.throws(()=>narrativePrompt({...req,scene:{text:'a'.repeat(10000)}},{budget:5000}),/No story content was truncated/);});
test('authoring JSON cannot pollute prototypes',()=>{assert.throws(()=>parseDraft('{"kind":"character","__proto__":{}}','character'),/Unsafe/);assert.throws(()=>parseDraft('{"kind":"story"}','character'),/wrong content type/);});
test('image prompt is independent of text provider and preserves explicit seed',()=>{const p=imagePrompt({kind:'portrait',character:{name:'Rhea',species:'Human',appearance:{muscle:200}},seed:1234});assert.equal(p.seed,1234);assert.ok(p.prompt.includes('muscle: 200'));assert.ok(p.prompt.includes('Fully clothed'));});
test('HTTP provider reports unavailable configuration without a fake fallback',async()=>{const p=new HttpProvider('text',{fetcher:async()=>new Response('{"error":"Configure a provider"}',{status:503})});await assert.rejects(p.generate(req),/Configure a provider/);});
test('proxy streams normalized narrative and deduplicates completed requests',async t=>{
  let calls=0,header;const {url}=await service(t,async(_u,options)=>{calls++;header=options.headers.Authorization;return new Response(stream('data: {"model":"test-model","choices":[{"delta":{"content":"Rhea waits."},"finish_reason":null}]}\n\ndata: {"choices":[{"delta":{},"finish_reason":"stop"}]}\n\ndata: [DONE]\n\n'),{headers:{'Content-Type':'text/event-stream'}});});
  const provider=new HttpProvider('text',{base:url+'/api/generate'}),chunks=[];const r=await provider.generate(req,{onChunk:c=>chunks.push(c)});assert.equal(r.text,'Rhea waits.');assert.deepEqual(chunks,['Rhea waits.']);assert.equal(r.model,'test-model');assert.equal(header,'Bearer server-secret-fixture');await provider.generate(req);assert.equal(calls,1);const status=await provider.status(req.action.id);assert.equal(status.state,'complete');assert.ok(!JSON.stringify(status).includes('server-secret-fixture'));
});
test('same request ID with changed prompt is rejected',async t=>{const {url}=await service(t,async()=>Response.json({choices:[{message:{content:'Hello'}}]}));const p=new HttpProvider('text',{base:url+'/api/generate'});await p.generate(req);await assert.rejects(p.generate({...req,player:{name:'Different'}}),/different input/);});
test('upstream truncation is unknown, not a successful partial commit',async t=>{const {url}=await service(t,async()=>new Response(stream('data: {"choices":[{"delta":{"content":"Partial"}}]}\n\n'),{headers:{'Content-Type':'text/event-stream'}}));const p=new HttpProvider('text',{base:url+'/api/generate'});await assert.rejects(p.generate(req),/before completion/);await assert.rejects(p.generate(req),/incomplete/);});
test('upstream errors do not expose credentials or remote error payloads',async t=>{const {url}=await service(t,async()=>new Response('server-secret-fixture',{status:401}));const r=await fetch(url+'/api/generate/text',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:req.action.id,request:req})});const body=await r.text();assert.ok(body.includes('HTTP 401'));assert.ok(!body.includes('server-secret-fixture'));});
test('service enforces same-origin and private-file boundaries',async t=>{const {url}=await service(t,async()=>Response.json({}));assert.equal((await fetch(url+'/.runtime/generation.json')).status,404);assert.equal((await fetch(url+'/api/providers',{headers:{Origin:'https://untrusted.invalid'}})).status,403);});
test('owned-raster image adapter never fetches arbitrary returned URLs',async t=>{let calls=0;const {url}=await service(t,async()=>{calls++;return Response.json({data:[{url:'http://169.254.169.254/secret'}]});},{IMAGE_ENDPOINT:'http://image.invalid/generate'});const p=new HttpProvider('image',{base:url+'/api/generate'});await assert.rejects(p.generate({kind:'portrait',character:{name:'Adult fixture'},requestId:'image-request-12345'}),/remote image URL was not fetched/);assert.equal(calls,1);});
test('atomic disk journal survives reopening and namespaces users',async t=>{const dir=await mkdtemp(join(tmpdir(),'ea3-journal-'));t.after(()=>rm(dir,{recursive:true,force:true}));const a=await new FileJournal(dir).open();await a.put('one',{id:'request-123',state:'complete',result:{text:'fixture'}});const b=await new FileJournal(dir).open();assert.equal((await b.get('one','request-123')).result.text,'fixture');assert.equal(await b.get('two','request-123'),null);});
