import test from 'node:test';import assert from 'node:assert/strict';
import {Session} from '../app/core/session.mjs';
import {compile} from '../app/core/schema.mjs';
import {createAdventure,planAction} from '../app/core/engine.mjs';
import {MemoryRepository} from './support/memory-repository.mjs';
import {starterStory,starterCharacters} from '../content/seed.mjs';
import {canonical,hash} from '../app/core/util.mjs';
import {makeTextProvider} from '../app/providers/registry.mjs';
async function setup(){const repo=new MemoryRepository(),compiled=compile(starterStory),save=createAdventure(compiled,starterCharacters,{name:'Test',rating:'sfw'});save.definitionKey=await repo.freeze(starterStory);await repo.commitSave(save);const session=new Session({save,compiled,repository:repo,provider:{id:'fixture',generate:async()=>({text:'A new response.'})}});return {repo,compiled,save,session};}
test('failed generation releases controls before its final error status',async()=>{const {session}=await setup();session.provider.generate=async()=>{throw Error('Fixture failure');};const statuses=[];session.onStatus=s=>statuses.push({...s,pending:!!session.pending});await assert.rejects(session.turn({kind:'continue'}),/Fixture/);assert.equal(statuses.at(-1).phase,'error');assert.equal(statuses.at(-1).pending,false);session.provider.generate=async()=>({text:'Retry works.'});await session.turn({kind:'continue'});assert.equal(session.save.events.length,2);});
test('Stop during accepted storage waits for the actual transaction outcome',async()=>{const {session,repo}=await setup(),commit=repo.commitSave.bind(repo);let entered,release;const started=new Promise(r=>entered=r),hold=new Promise(r=>release=r);repo.commitSave=async(...args)=>{await commit(...args);entered();await hold;};const pending=session.turn({kind:'continue'});await started;session.stop();assert.ok(session.pending);await assert.rejects(session.turn({kind:'continue'}),/already in progress/);await assert.rejects(session.rewind(1),/finishing/);release();await pending;assert.equal(session.pending,null);assert.equal(session.save.events.length,2);assert.equal((await repo.readSave(session.save.id)).events.length,2);});
test('Stop before the storage guard prevents a pending commit',async()=>{const {session,repo}=await setup(),commit=repo.commitSave.bind(repo);let entered,release;const started=new Promise(r=>entered=r),hold=new Promise(r=>release=r);repo.commitSave=async(...args)=>{entered();await hold;return commit(...args);};const pending=session.turn({kind:'continue'});await started;session.stop();release();await assert.rejects(pending,e=>e.name==='AbortError');assert.equal(session.save.events.length,1);assert.equal((await repo.readSave(session.save.id)).events.length,1);});
test('archive refuses image references missing only from past history',async()=>{const {repo,session}=await setup(),a=await repo.putAsset({data:'data:image/png;base64,AA=='}),b=await repo.putAsset({data:'data:image/png;base64,AQ=='});await session.turn({kind:'image',subject:'scene',assetId:a.id});await session.turn({kind:'image',subject:'scene',assetId:b.id});const envelope=await repo.exportArchive({saveId:session.save.id});envelope.payload.tables.assets=envelope.payload.tables.assets.filter(r=>r.key!==a.id);envelope.hash=await hash(canonical(envelope.payload));await assert.rejects(repo.inspectArchive(envelope),/Missing referenced image/);});
test('copying an adventure retains unselected gallery images in export',async()=>{const {repo,save}=await setup(),a=await repo.putAsset({data:'data:image/png;base64,AA==',links:{['save:'+save.id]:true}});const copy=await repo.copySave(save);assert.ok((await repo.exportArchive({saveId:copy.id})).payload.tables.assets.some(r=>r.key===a.id));});
test('transport checkpoints do not recursively inflate complete archives',async()=>{const {repo}=await setup();await repo.put('drafts','transfer:outgoing:x',{archive:await repo.exportArchive()});await repo.put('drafts','editor:story:mine',{value:'keep my draft'});const a=await repo.exportArchive();assert.deepEqual(a.payload.tables.drafts.map(r=>r.key),['editor:story:mine']);});
test('a final ending blocks further narrative and economic actions',()=>{const story=structuredClone(starterStory);story.afterEnding='stop';story.nodes[0].ending='Complete';const compiled=compile(story),save=createAdventure(compiled,starterCharacters,{name:'Test',rating:'sfw'});for(const kind of ['say','continue','auto','choice','travel','offer','recruit'])assert.throws(()=>planAction(compiled,save,{kind,text:'continue'}),/ended/);});
test('saved player guidance reaches the independent provider request',async()=>{let received;const prior=globalThis.fetch;globalThis.fetch=async(_url,options)=>{received=JSON.parse(options.body);return new Response(JSON.stringify({text:'A fixture reply.'}));};try{const p=makeTextProvider({textProvider:'http',guidance:'Let the characters lead.'});await p.generate({schema:'ea3/narration/1'});assert.equal(received.request.guidance,'Let the characters lead.');}finally{globalThis.fetch=prior;}});
