import {test} from 'node:test';import assert from 'node:assert/strict';import {TransferSender,TransferReceiver,prepareTransfer} from '../app/transfer-core.mjs';
class Channel extends EventTarget{readyState='open';bufferedAmount=0;sent=[];send(data){assert.equal(this.readyState,'open');this.sent.push(JSON.parse(data));const deliver=()=>this.peer.dispatchEvent(new MessageEvent('message',{data}));if(this.filter?.(JSON.parse(data),deliver)===false)return;queueMicrotask(deliver);}close(){this.readyState='closed';}}
const pair=()=>{const a=new Channel(),b=new Channel();a.peer=b;b.peer=a;return[a,b];};
const timeout=(promise,ms=1500)=>Promise.race([promise,new Promise((_,reject)=>{const t=setTimeout(()=>reject(Error('Test timed out')),ms);t.unref();})]);
const fixture=async()=>prepareTransfer({schema:'synthetic-test',data:'A 🌿'.repeat(24000)},{title:'Transfer contract fixture'});
test('two isolated endpoints transfer only after consent, persist before ACK and complete integrity',async()=>{const prepared=await fixture(),[a,b]=pair(),parts=[],order=[];let approvalResolve,imported=0;const done=new Promise((resolve,reject)=>{const receiver=new TransferReceiver(b,{approve:()=>new Promise(r=>approvalResolve=r),persist:async r=>{if(r.type==='chunk'){parts.push(r);order.push('persist:'+r.index);}},importArchive:async archive=>{imported++;assert.equal(archive.data,'A 🌿'.repeat(24000));return {imported:1};},onError:reject});b.filter=m=>{if(m.type==='ack')assert.ok(parts.length>=m.next);};const sender=new TransferSender(a,prepared,{onComplete:r=>{sender.close();receiver.close();resolve(r);},onError:reject,ackTimeout:50});sender.offer();setTimeout(()=>{assert.equal(a.sent.filter(m=>m.type==='chunk').length,0);approvalResolve(true);},5);});await timeout(done);assert.equal(imported,1);assert.equal(parts.length,prepared.manifest.chunks);});
test('dropped acknowledgements and duplicate delivery have bounded retries without duplicate import',async()=>{const prepared=await fixture(),[a,b]=pair();let imported=0,drops=0;const done=new Promise((resolve,reject)=>{const receiver=new TransferReceiver(b,{approve:async()=>true,importArchive:async()=>{imported++;return{};},onError:reject});b.filter=(m,deliver)=>{if(m.type==='ack'&&drops++<12)return false;if(m.type==='ack')queueMicrotask(deliver);};const sender=new TransferSender(a,prepared,{ackTimeout:20,maxRetries:3,onComplete:()=>{sender.close();receiver.close();resolve();},onError:reject});sender.offer();});await timeout(done);assert.equal(imported,1);});
test('interrupted transfer resumes persisted chunks after independent protocol restart',async()=>{const prepared=await fixture(),stored=[],[a,b]=pair();let interrupted;const first=new Promise(resolve=>interrupted=resolve);const receiver=new TransferReceiver(b,{approve:async()=>true,persist:async r=>{if(r.type==='chunk'){stored.push(r);if(stored.length===3){a.close();b.close();sender.close();receiver.close();interrupted();}}},onError:()=>{}});const sender=new TransferSender(a,prepared,{onError:()=>{}});sender.offer();await timeout(first);const [c,d]=pair();let imports=0;await timeout(new Promise((resolve,reject)=>{const resumed=new TransferReceiver(d,{approve:async()=>true,load:async()=>stored,persist:async r=>{if(r.type==='chunk')stored.push(r);},importArchive:async()=>{imports++;return{};},onError:reject});const out=new TransferSender(c,prepared,{ackTimeout:30,onError:reject,onComplete:()=>{out.close();resumed.close();resolve();}});out.offer();}));assert.equal(imports,1);assert.equal(c.sent.find(m=>m.type==='chunk').index,3);});
test('corrupted bytes never reach import and sender retains its buffer',async()=>{const prepared=await fixture(),[a,b]=pair();let imported=0;a.filter=(m,deliver)=>{if(m.type==='chunk'&&m.index===0){m.data='Qg=='+m.data.slice(4);queueMicrotask(()=>b.dispatchEvent(new MessageEvent('message',{data:JSON.stringify(m)})));return false;}};await timeout(new Promise(resolve=>{const receiver=new TransferReceiver(b,{approve:async()=>true,importArchive:async()=>{imported++;},onError:()=>{sender.close();receiver.close();resolve();}});const sender=new TransferSender(a,prepared,{onError:()=>resolve()});sender.offer();}));assert.equal(imported,0);assert.ok(prepared.bytes.length>1000);});
test('duplicate non-progress ACKs cannot reset retry budget forever',async()=>{const prepared=await fixture(),[a,b]=pair();let interval;await timeout(new Promise((resolve,reject)=>{const sender=new TransferSender(a,prepared,{ackTimeout:15,maxRetries:2,onComplete:()=>reject(Error('Unexpected completion')),onError:e=>{clearInterval(interval);assert.match(e.message,/timed out/);resolve();}});b.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.type==='offer'){b.send(JSON.stringify({type:'accept',id:m.id,next:0}));interval=setInterval(()=>b.send(JSON.stringify({type:'ack',id:m.id,next:0})),3);}});sender.offer();}));});
test('declined archive sends zero data chunks',async()=>{const prepared=await fixture(),[a,b]=pair();await timeout(new Promise(resolve=>{const receiver=new TransferReceiver(b,{approve:async()=>false});const sender=new TransferSender(a,prepared,{onError:()=>{sender.close();receiver.close();resolve();}});sender.offer();}));assert.equal(a.sent.filter(m=>m.type==='chunk').length,0);});
