import test from 'node:test';
import assert from 'node:assert/strict';
import {NarrationVoice} from '../app/voice.mjs';
import {FolderBackup} from '../app/storage/folder-backup.mjs';
import {MemoryRepository} from './support/memory-repository.mjs';
function speech(){const spoken=[];const synthesis={speak:u=>spoken.push(u),cancel(){this.cancelled=true;},pause(){this.paused=true;},resume(){this.paused=false;},getVoices:()=>[{voiceURI:'a'},{voiceURI:'b'}]};class Utterance{constructor(text){this.text=text;}}return{spoken,synthesis,voice:new NarrationVoice(synthesis,Utterance)};}
test('long narration is queued completely rather than truncated',()=>{const {voice,spoken}=speech(),text='A long road winds through the hills. '.repeat(100);voice.read(text);let read='';while(voice.state==='speaking'){const u=spoken.at(-1);assert.ok(u.text.length<=650);read+=u.text+' ';u.onend();}assert.equal(read.replace(/\s/g,''),text.replace(/\s/g,''));});
test('stop invalidates late speech callbacks',()=>{const{voice,spoken}=speech();voice.read('Word '.repeat(600));const u=spoken.at(-1);voice.stop();u.onend();assert.equal(voice.state,'idle');assert.equal(spoken.length,1);});
test('explicit speaker paragraphs receive assignments, unmarked text uses narrator',()=>{const{voice,spoken}=speech();voice.read('The fire glows.\n\nMira: Welcome back.',{voiceAssignments:{Narrator:'a',Mira:'b'}});assert.equal(spoken[0].voice.voiceURI,'a');spoken[0].onend();assert.equal(spoken[1].voice.voiceURI,'b');assert.equal(spoken[1].text,'Welcome back.');});
test('pause, resume and replay preserve user control',()=>{const{voice,synthesis,spoken}=speech();voice.read('A welcome.');voice.pause();assert.equal(voice.state,'paused');assert.equal(synthesis.paused,true);voice.resume();assert.equal(voice.state,'speaking');voice.stop();voice.replay();assert.equal(spoken.at(-1).text,'A welcome.');});
test('unavailable speech is visible rather than silently simulated',()=>{assert.throws(()=>new NarrationVoice(null,null).read('Hello'),/does not provide/);});
function folder(){const data=new Map();let fail=false;const handle={kind:'directory',queryPermission:async()=>handle.permission,requestPermission:async()=>handle.permission,permission:'granted',getDirectoryHandle:async()=>handle,getFileHandle:async name=>({createWritable:async()=>({write:async text=>{if(fail)throw new Error('Disk full');data.set(name,text);},close:async()=>{},abort:async()=>{}}),getFile:async()=>new Blob([data.get(name)])})};return {handle,data,setFail:v=>{fail=v;}};}
test('folder backups alternate verified slots and preserve previous valid copy on failure',async()=>{const repo=new MemoryRepository(),f=folder(),b=new FolderBackup(repo);b.handle=f.handle;b.enabled=true;await b.write();const first=b.status.filename,raw=f.data.get(first);await b.write();assert.notEqual(b.status.filename,first);assert.equal(f.data.size,2);f.setFail(true);await assert.rejects(b.write(),/Disk full/);assert.equal(f.data.get(first),raw);assert.equal(b.status.state,'error');});
test('background backup never prompts for lost permission',async()=>{const repo=new MemoryRepository(),f=folder(),b=new FolderBackup(repo);b.handle=f.handle;b.enabled=true;f.handle.permission='prompt';let prompted=false;f.handle.requestPermission=async()=>{prompted=true;return'granted';};await assert.rejects(b.write(),/permission/);assert.equal(prompted,false);assert.equal(b.status.state,'permission-needed');await b.write({requestPermission:true});assert.equal(prompted,true);assert.equal(b.status.state,'ready');});
test('disconnect retains verified backup files',async()=>{const repo=new MemoryRepository(),f=folder(),b=new FolderBackup(repo);b.handle=f.handle;b.enabled=true;await b.write();await b.disconnect();assert.equal(b.enabled,false);assert.equal(f.data.size,1);});
