import {CommunityClient} from './community.mjs';
import {Repository} from './storage/repository.mjs';
import {signInDialog} from './ui/community-auth.mjs';
import {validateContent} from './core/schema.mjs';
import {safeJSON,download,requireThat} from './core/util.mjs';
import {narrativePrompt,imagePrompt,authoringPrompt} from './providers/prompts.mjs';
import {$,esc,button,badge,image,field,modal,confirmDialog,empty,toast,onError,formatDate} from './ui/dom.mjs';
const mode=document.body.dataset.console || 'workbench',client=new CommunityClient();
let user=null,repo=null,epoch=0,state='open',currentReport=null;
const root=$('#console-root');
function shell(body){root.innerHTML=`<header class="console-top"><a href="/" class="brand"><strong>EmberAdventures<sup>3</sup></strong></a><span class="badge warm">${mode==='operator'?'Operator':'Developer Workbench'}</span><div class="row wrap">${user?badge(user.username)+' '+badge(user.role):''}<a class="button small" href="/">Back to game</a>${button(user?'console-signout':'console-signin',user?'Sign out':'Sign in','user','small')}</div></header><main class="console-page">${body}</main>`;}
async function boot(){try{const session=await client.session();user=session.user;if(mode==='operator')await operator();else await workbench();}catch(error){shell(empty('Service unavailable',error.message+' Local player data has not been modified.',button('console-refresh','Try again','refresh')));}}
async function operator(){
 if(!user||!['moderator','admin'].includes(user.role)||user.restricted){shell(`<div class="console-intro"><div class="eyebrow">Protected workspace</div><h1>Review the version that was reported.</h1><p>Moderation access is checked by the server on every request. A player account cannot grant itself operator privileges.</p></div>${empty('Operator access required','Sign in with a moderator or administrator account. The trusted local operator assigns roles using the documented command-line tool.',button('console-signin','Sign in','user','primary'))}`);return;}
 const token=++epoch,data=await client.request('/api/admin/reports?state='+state);if(token!==epoch)return;
 shell(`<div class="console-intro"><div class="eyebrow">Moderation workspace</div><h1>Reports & resolutions</h1><p>Inspect immutable reported content, take a specific corrective action, and leave a clear audit trail.</p></div><div class="console-toolbar">${button('operator-open','Open reports','flag',state==='open'?'primary':'')}${button('operator-resolved','Resolved reports','check',state==='resolved'?'primary':'')}<span class="muted">${data.total} reports</span></div><div class="operator-layout"><section class="console-card report-list">${data.reports.map(r=>`<button class="report-row" data-action="operator-inspect" data-report="${esc(r.id)}"><span class="eyebrow">${esc(r.reason)} · ${esc(r.state)}</span><strong>${esc(r.name)}</strong><small>Version ${r.number} · ${esc(r.uploader)}<br>${formatDate(r.created_at)}</small></button>`).join('')||empty('The queue is clear','Reports appear here when a signed-in player submits a problem with an exact version.')}</section><section class="console-card" id="operator-detail">${empty('Select a report','Its original definition, images, uploader and action history will appear here.')}</section></div>`);
 if(currentReport&&data.reports.some(r=>r.id===currentReport))await inspectReport(currentReport);
}
async function inspectReport(id){
 currentReport=id;const detail=await client.request('/api/admin/reports/'+encodeURIComponent(id));if(currentReport!==id)return;
 const r=detail.report,v=detail.version.summary,c=detail.reportedContent,el=$('#operator-detail');
 el.innerHTML=`<div class="eyebrow">Exact reported version ${v.number}</div><h2>${esc(c.title||c.name)}</h2><div class="report-summary"><div>${image(c.image,c.title||c.name,'report-art')}</div><div><p><strong>${esc(r.reason)}</strong><br>${esc(r.details)}</p><small>Reporter: ${esc(r.reporter)}<br>Uploader: ${esc(detail.uploader.username)} · ${detail.uploader.restricted?'restricted':'active'}<br>Reply contact: ${esc(r.contact||'Not provided')}<br>Original hash: ${detail.snapshotMatches?'verified':'mismatch — investigate'}<br>Current classification: ${esc(v.rating)}</small></div></div><details class="console-json"><summary>Inspect original JSON (immutable)</summary><pre>${esc(JSON.stringify(c,null,2))}</pre></details><form id="operator-action" class="stack"><h3>Take a corrective action</h3>${field('Action','action','hide',{options:[['hide','Hide this exact version'],['restore','Restore this exact version'],['reclassify','Correct classification'],['lock','Lock publication updates'],['unlock','Unlock publication updates'],['restrict-uploader','Restrict uploader'],['unrestrict-uploader','Remove uploader restriction'],['feature','Feature this publication'],['unfeature','Remove featured status'],['resolve','Resolve report'],['reopen','Reopen report'],['reply-draft','Save a reply draft']]})}${field('Classification for reclassification','rating',v.rating,{options:[['sfw','SFW'],['mature','Mature']]})}${field('Action explanation / reply draft','note','',{type:'textarea',rows:4,required:true,extra:'minlength="8" maxlength="6000"'})}<button type="submit" class="button primary">Review & apply action</button></form><section class="console-history"><h3>Resolution history</h3>${detail.history.map(a=>`<article><strong>${esc(a.action)}</strong> <small>${esc(a.actor)} · ${formatDate(a.at)}</small><p>${esc(a.note)}</p></article>`).join('')||'<p class="muted">No action recorded yet.</p>'}</section><section class="notice info"><strong>Reply draft — ${r.reply_sent_at?'marked sent externally':'not sent'}</strong><p>${esc(r.reply_draft||'No reply drafted.')}</p><small>This tool does not send email. Copy the draft into your own email application after reviewing the action history.</small>${r.reply_draft?button('operator-copy-reply','Copy reply draft','folder','small'):''}</section>`;
 el.querySelector('#operator-action').onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target)),submit=$('button[type="submit"]',e.target);if(!await confirmDialog('Apply this moderation action?',`${data.action} on “${c.title||c.name}”, version ${v.number}. This updates the current instance and records your explanation.`,{confirm:'Apply action',danger:['hide','restrict-uploader','lock'].includes(data.action)}))return;submit.disabled=true;try{await client.request('/api/admin/reports/'+id,{method:'POST',body:data});toast('Action recorded. No email was sent.');await inspectReport(id);}catch(error){onError(error);submit.disabled=false;}};
 const copy=$('[data-action="operator-copy-reply"]',el);if(copy)copy.onclick=async()=>{try{await navigator.clipboard.writeText(r.reply_draft);toast('Reply draft copied. It has not been sent.');}catch{modal('Copy reply draft',field('Reply draft','reply',r.reply_draft,{type:'textarea',rows:7,extra:'readonly'}));}};
}
async function workbench(){
 if(!repo)repo=await new Repository().open();const [provider,jobs,items]=await Promise.all([client.request('/api/providers'),repo.all('jobs'),repo.listContent()]);
 shell(`<div class="console-intro"><div class="eyebrow">Local development tools</div><h1>See what the game is doing.</h1><p>Inspect your own requests and definitions. Credentials stay on the server; private moderation data requires operator access.</p></div><div class="console-workbench"><section class="console-card"><h2>Provider connections</h2><p class="editor-help">Configuration is not proof of a successful live model call. Unsupported capabilities stay visible.</p><pre class="console-code">${esc(JSON.stringify(provider,null,2))}</pre><div class="row wrap">${button('console-refresh','Refresh status','refresh')}<a class="button" href="/operator.html">Operator workspace</a>${button('server-traces','Protected server traces','shield')}</div></section><section class="console-card"><h2>Local requests & recovery</h2><p class="editor-help">Requests are persisted before dispatch. An unknown result is not retried automatically.</p><div class="console-jobs">${jobs.map(j=>`<div class="list-row"><div class="grow"><strong>${esc(j.kind||j.provider||'Generation')}</strong><p>${esc(j.state)} · ${esc(j.error||'')}</p></div>${button('job-inspect','Inspect','search','small',`data-job="${esc(j.id)}"`)}${button('job-reconcile','Check result','refresh','small',`data-job="${esc(j.id)}"`)}</div>`).join('')||'<p class="muted">No unfinished requests.</p>'}</div></section><section class="console-card console-span"><h2>Definition validation</h2><p class="editor-help">Validate a local definition without modifying it. Exports remain under your control.</p><form id="validate-form" class="stack">${field('Local definition','content','',{options:[['','Choose a library item'],...items.map(c=>[c.kind+':'+c.id,c.title])]})}${field('Definition JSON','definition','',{type:'textarea',rows:12})}<button class="button primary" type="submit">Validate definition</button><pre id="validation-result" role="status"></pre></form></section></div>`);
 const selector=$('[name="content"]');selector.onchange=async()=>{if(!selector.value)return;const i=selector.value.indexOf(':'),c=await repo.getContent(selector.value.slice(0,i),selector.value.slice(i+1));$('[name="definition"]').value=JSON.stringify(c,null,2);};
 $('#validate-form').onsubmit=e=>{e.preventDefault();try{const c=safeJSON($('[name="definition"]').value),errors=validateContent(c);$('#validation-result').textContent=errors.length?errors.join('\n'):'Valid '+c.kind+' definition. No local content was changed.';}catch(error){$('#validation-result').textContent=error.message;}};
}
async function inspectJob(id){const job=await repo.get('jobs',id);requireThat(job,'This request was already removed.');let prompt;
 try{if(job.kind!=='publication'){const r=job.request;if(r?.schema==='ea3/narration/1')prompt=narrativePrompt(r);else if(r?.draft)prompt=authoringPrompt(r);else if(r?.kind)prompt=imagePrompt(r);}}catch(error){prompt={error:error.message};}
 const d=modal('Local request details',`<p class="editor-help">This may include your private story. It is shown locally, not automatically uploaded or added to a report.</p><details open class="console-json"><summary>Persisted request</summary><pre>${esc(JSON.stringify(job,null,2))}</pre></details>${prompt?`<details class="console-json"><summary>Rendered provider prompt</summary><pre>${esc(JSON.stringify(prompt,null,2))}</pre></details>`:''}`,{wide:true,footer:button('job-export','Export this record','download')});d.on('click','[data-action="job-export"]',()=>download('EA3-private-request-'+id+'.json',{job,prompt}));}
async function reconcileJob(id){const job=await repo.get('jobs',id);requireThat(job,'This request is no longer pending.');if(job.kind==='publication'){await client.session();if(!await signInDialog(client))return;const r=await client.reconcile(repo,job);toast(r.warning||'Publication receipt reconciled.');await workbench();return;}
 requireThat(job.provider!=='perchance','Perchance job reconciliation requires the original host journal. Use the host export documented in Providers; no new request was dispatched.');
 const r=await client.request('/api/generate/status/'+encodeURIComponent(job.id));modal('Recorded generation status',`<pre class="console-code">${esc(JSON.stringify(r,null,2))}</pre><p class="editor-help">This result is not automatically applied to the story. The original revision may no longer be current.</p>`,{wide:true});}
const actions={
 'console-refresh':boot,'console-signin':async()=>{client.user=null;if(await signInDialog(client))await boot();},'console-signout':async()=>{await client.signOut();await boot();},
 'operator-open':async()=>{state='open';currentReport=null;await operator();},'operator-resolved':async()=>{state='resolved';currentReport=null;await operator();},'operator-inspect':t=>inspectReport(t.dataset.report),
 'job-inspect':t=>inspectJob(t.dataset.job),'job-reconcile':t=>reconcileJob(t.dataset.job),'server-traces':async()=>{const data=await client.request('/api/admin/traces');modal('Protected server traces',`<pre class="console-code">${esc(JSON.stringify(data,null,2))}</pre>`,{wide:true});}
};
document.addEventListener('click',e=>{const t=e.target.closest('[data-action]'),fn=t&&actions[t.dataset.action];if(fn){e.preventDefault();Promise.resolve().then(()=>fn(t)).catch(onError);}});
boot();
