/* Deliberately independent of the game modules and schemas. Read-only rescue, not automatic repair. */
(()=>{'use strict';let rescue=null;const status=document.querySelector('#status'),report=document.querySelector('#report'),save=document.querySelector('#export');
const result=r=>new Promise((resolve,reject)=>{r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
document.querySelector('#inspect').onclick=async()=>{let db;try{status.textContent='Reading existing local records…';if(!globalThis.indexedDB)throw new Error('IndexedDB is not available in this browser.');if(indexedDB.databases){const names=await indexedDB.databases();if(!names.some(d=>d.name==='emberadventures3'))throw new Error('No EmberAdventures 3 database exists on this origin. Open recovery on the same site and browser where you played.');}
const opening=indexedDB.open('emberadventures3');opening.onupgradeneeded=()=>opening.transaction.abort();db=await result(opening);rescue={schema:'ea3/rescue/1',createdAt:new Date().toISOString(),database:'emberadventures3',tables:{},errors:[]};
for(const name of db.objectStoreNames){if(name==='handles')continue;try{rescue.tables[name]=await result(db.transaction(name,'readonly').objectStore(name).getAll());}catch(e){rescue.errors.push({table:name,error:e.message});}}
report.textContent=JSON.stringify({tables:Object.fromEntries(Object.entries(rescue.tables).map(([k,v])=>[k,v.length])),errors:rescue.errors},null,2);save.disabled=false;status.textContent=rescue.errors.length?'Some records could not be read. Download the surviving records before attempting any repair.':'Read-only inspection complete. No stored data was changed.';
}catch(e){status.textContent=e.message;}finally{db?.close();}};
save.onclick=()=>{if(!rescue)return;const url=URL.createObjectURL(new Blob([JSON.stringify(rescue)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='EmberAdventures-raw-rescue-'+new Date().toISOString().slice(0,10)+'.json';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),10000);status.textContent='Raw rescue download prepared. Keep it before attempting repairs.';};})();
