import {requireThat} from '../core/util.mjs';
export const NODE_WIDTH=262;
export const NODE_HEIGHT=136;
export const COLUMN=340;
export const ROW=185;
export function edgesOf(story){const edges=[];for(const n of story.nodes){if(n.next)edges.push({id:n.id+':next',from:n.id,to:n.next,label:'Continue',kind:'next'});for(const c of n.choices || [])if(c.to)edges.push({id:c.id,from:n.id,to:c.to,label:c.label,kind:'choice'});}return edges;}
/** Iterative breadth-first layout: cyclic and disconnected graphs do not recurse forever. */
export function autoLayout(story){const edges=edgesOf(story),outgoing=new Map(story.nodes.map(n=>[n.id,[]])),levels=new Map(),positions={};for(const e of edges)outgoing.get(e.from)?.push(e.to);let queue=[story.start],head=0;levels.set(story.start,0);while(head<queue.length){const from=queue[head++];for(const to of outgoing.get(from)||[])if(outgoing.has(to)&&!levels.has(to)){levels.set(to,levels.get(from)+1);queue.push(to);}}const depths=new Map(),last=[...levels.values()].reduce((max,v)=>Math.max(max,v),0);let disconnected=0;for(const n of story.nodes){const level=levels.has(n.id)?levels.get(n.id):last+2+Math.floor(disconnected++/12),row=depths.get(level)||0;depths.set(level,row+1);positions[n.id]={x:80+level*COLUMN,y:80+row*ROW};}return positions;}
export class GraphIndex{
 constructor(story){this.story=story;this.nodes=new Map(story.nodes.map(n=>[n.id,n]));this.edges=edgesOf(story);const automatic=autoLayout(story);this.positions={...automatic,...story.editor?.positions};this.buckets=new Map();this.byNode=new Map();for(const n of story.nodes){const p=this.positions[n.id];if(!p||!Number.isFinite(p.x)||!Number.isFinite(p.y))this.positions[n.id]=automatic[n.id];this.index(n.id);}for(const e of this.edges){for(const k of [e.from,e.to]){if(!this.byNode.has(k))this.byNode.set(k,[]);this.byNode.get(k).push(e);}}}
 index(id){const p=this.positions[id],key=Math.floor(p.x/COLUMN)+','+Math.floor(p.y/ROW);if(!this.buckets.has(key))this.buckets.set(key,new Set());this.buckets.get(key).add(id);}
 move(id,x,y){requireThat(this.nodes.has(id)&&Number.isFinite(x)&&Number.isFinite(y),'Invalid graph position.');const p=this.positions[id],key=Math.floor(p.x/COLUMN)+','+Math.floor(p.y/ROW);this.buckets.get(key)?.delete(id);this.positions[id]={x:Math.round(x),y:Math.round(y)};this.index(id);}
 visible({x,y,width,height,zoom},limit=600){const left=-x/zoom-NODE_WIDTH,top=-y/zoom-NODE_HEIGHT,right=(width-x)/zoom+NODE_WIDTH,bottom=(height-y)/zoom+NODE_HEIGHT,ids=new Set();for(let a=Math.floor(left/COLUMN);a<=Math.floor(right/COLUMN);a++)for(let b=Math.floor(top/ROW);b<=Math.floor(bottom/ROW);b++)for(const id of this.buckets.get(a+','+b)||[])ids.add(id);const all=[...ids];return{nodes:all.slice(0,limit).map(id=>this.nodes.get(id)),total:all.length,detailLimit:limit};}
 search(query,offset=0,limit=60){const q=String(query).trim().toLowerCase(),result=[];for(const n of this.story.nodes)if(!q||`${n.title || ''} ${n.text || ''}`.toLowerCase().includes(q))result.push(n);return{nodes:result.slice(offset,offset+limit),total:result.length};}
 bounds(){let left=Infinity,top=Infinity,right=-Infinity,bottom=-Infinity;for(const p of Object.values(this.positions)){left=Math.min(left,p.x);top=Math.min(top,p.y);right=Math.max(right,p.x+NODE_WIDTH);bottom=Math.max(bottom,p.y+NODE_HEIGHT);}return{left,top,right,bottom,width:right-left,height:bottom-top};}
}
