import {clone,id,validKey,requireThat,isRecord} from '../core/util.mjs';
import {SCHEMA,validateContent,EFFECTS,CONDITIONS} from '../core/schema.mjs';

const has=(object,key)=>Object.prototype.hasOwnProperty.call(object,key);
const validSegment=s=>Number.isSafeInteger(s)&&s>=0||validKey(s);
function parentAt(root,path){requireThat(Array.isArray(path)&&path.length&&path.every(validSegment),'Invalid editor path.');let value=root;for(const key of path.slice(0,-1)){requireThat(value!==null&&typeof value==='object'&&has(value,key),'The selected field no longer exists.');value=value[key];}return [value,path.at(-1)];}
export function valueAt(root,path){let value=root;for(const key of path){requireThat(validSegment(key),'Invalid editor path.');value=value?.[key];}return value;}
/** Editor history is separate from the player's canonical timeline. Only changed fields are retained. */
export class DraftModel {
  constructor(content,{onChange=()=>{},historyLimit=100}={}){this.value=clone(content);this.past=[];this.future=[];this.revision=0;this.savedRevision=0;this.onChange=onChange;this.historyLimit=historyLimit;this.batch=null;}
  get dirty(){return this.revision!==this.savedRevision;}
  record(operation){if(this.batch){this.batch.operations.push(operation);return;}this.past.push({label:operation.label || 'Edit',operations:[operation]});if(this.past.length>this.historyLimit)this.past.shift();this.future=[];this.revision++;this.onChange(this);}
  set(path,value,label='Edit field'){
    requireThat(Array.isArray(path)&&path.every(validSegment),'Invalid editor path.');
    if(!path.length){const before=this.value;this.value=clone(value);this.record({kind:'root',before,after:clone(value),label});return;}
    const [parent,key]=parentAt(this.value,path);requireThat(parent!==null&&typeof parent==='object','Invalid parent field.');
    const before=has(parent,key)?clone(parent[key]):undefined,exists=has(parent,key);if(exists&&JSON.stringify(before)===JSON.stringify(value))return;
    if(value===undefined)delete parent[key];else parent[key]=clone(value);
    this.record({kind:'set',path:[...path],before,after:clone(value),exists,afterExists:value!==undefined,label});
  }
  splice(path,index,remove,...items){const list=valueAt(this.value,path);requireThat(Array.isArray(list)&&Number.isSafeInteger(index)&&index>=0&&index<=list.length&&Number.isSafeInteger(remove)&&remove>=0,'Invalid list edit.');const removed=list.splice(index,remove,...clone(items));this.record({kind:'splice',path:[...path],index,removed:clone(removed),inserted:clone(items),label:'Change list'});}
  transaction(label,edit){requireThat(!this.batch,'Nested editor transaction.');this.batch={label,operations:[]};try{edit();const operation=this.batch;this.batch=null;if(operation.operations.length){this.past.push(operation);if(this.past.length>this.historyLimit)this.past.shift();this.future=[];this.revision++;this.onChange(this);}}catch(e){const operation=this.batch;this.batch=null;for(const op of [...operation.operations].reverse())this.replay(op,false);throw e;}}
  replay(op,forward){if(op.kind==='root'){this.value=clone(forward?op.after:op.before);return;}if(op.kind==='set'){const[p,k]=parentAt(this.value,op.path);if(forward?op.afterExists:op.exists)p[k]=clone(forward?op.after:op.before);else delete p[k];}else{const list=valueAt(this.value,op.path);list.splice(op.index,forward?op.removed.length:op.inserted.length,...clone(forward?op.inserted:op.removed));}}
  undo(){const entry=this.past.pop();if(!entry)return;for(const op of [...entry.operations].reverse())this.replay(op,false);this.future.push(entry);this.revision++;this.onChange(this);}
  redo(){const entry=this.future.pop();if(!entry)return;for(const op of entry.operations)this.replay(op,true);this.past.push(entry);this.revision++;this.onChange(this);}
  markSaved(){this.savedRevision=this.revision;}
  errors(){return validateContent(this.value);}
  addNode(){const n={id:id('scene'),title:'New story moment',text:'Describe what happens here.',location:this.value.locations[0]?.id || '',choices:[]};this.splice(['nodes'],this.value.nodes.length,0,n);return n.id;}
  duplicateNode(nodeId){const i=this.value.nodes.findIndex(n=>n.id===nodeId);requireThat(i>=0,'Select a story node.');const n=clone(this.value.nodes[i]);n.id=id('scene');n.title=(n.title || 'Story moment')+' · copy';n.choices=(n.choices || []).map(c=>({...c,id:id('choice')}));this.splice(['nodes'],i+1,0,n);return n.id;}
  inbound(nodeId){return this.value.nodes.flatMap(n=>[...(n.next===nodeId?[{nodeId:n.id,label:'Continue'}]:[]),...(n.choices || []).filter(c=>c.to===nodeId).map(c=>({nodeId:n.id,choiceId:c.id,label:c.label}))]);}
  removeNode(nodeId){const index=this.value.nodes.findIndex(n=>n.id===nodeId);requireThat(index>=0,'The story node no longer exists.');requireThat(this.value.nodes.length>1,'A story must have at least one moment.');requireThat(nodeId!==this.value.start,'Choose another opening before deleting this moment.');this.transaction('Delete story moment',()=>{for(let n=0;n<this.value.nodes.length;n++){const node=this.value.nodes[n];if(node.next===nodeId)this.set(['nodes',n,'next'],undefined);for(let c=0;c<(node.choices || []).length;c++)if(node.choices[c].to===nodeId)this.set(['nodes',n,'choices',c,'to'],undefined);}this.splice(['nodes'],index,1);});}
}
export function newContent(kind){const base={schema:SCHEMA,kind,id:id(kind),rating:'sfw',description:'',creator:'',genre:'Fantasy',tags:[],image:''};if(kind==='character')return {...base,name:'New character',age:25,pronouns:'they/them',species:'Human',personality:'Describe their personality, motivations and quirks.',speech:'',backstory:'',opening:'',appearance:{description:''},wardrobe:[{id:id('outfit'),name:'Everyday clothes',description:'Comfortable travel clothes.',rating:'sfw'}]};const location=id('location'),start=id('scene');return {...base,title:'Untitled adventure',initiative:'shared',start,cast:[],backgroundCast:[],rules:'',afterEnding:'freeplay',nodes:[{id:start,title:'An unexpected invitation',text:'The warmth of the inn spills across the rain-soaked road. Someone inside has been waiting for you.',location,choices:[]}],locations:[{id:location,name:'The Lantern Inn',description:'A warm refuge at the crossroads.',discovered:true,links:[]}],initial:{resources:{coin:20},inventory:{},flags:{},relationships:{}},items:[],offers:[],developments:[],effectGroups:{}};}
export function defaultEffect(type='flag'){requireThat(EFFECTS.includes(type),'Unknown effect type.');if(['resource','item','relationship'].includes(type))return {type,key:type==='resource'?'coin':'',amount:1};if(type==='clock')return{type,amount:1};if(type==='ending')return{type,value:'The end'};if(['memory','outfit','unlockOutfit','equip'].includes(type))return{type,key:type==='memory'?'world':'',value:'',...(type==='equip'?{slot:'hand'}:{})};if(type==='presence')return{type,key:'',value:true};if(type==='flag')return{type,key:'new_flag',value:true};return{type,key:''};}
export function defaultCondition(type='flag'){requireThat(CONDITIONS.includes(type),'Unknown condition type.');if(['all','any','not'].includes(type))return{type,conditions:[]};return{type,...(type!=='clock'?{key:type==='resource'?'coin':''}:{}),op:['resource','item','relationship','clock'].includes(type)?'gte':'eq',value:['resource','item','relationship','clock'].includes(type)?1:true};}
export function proposalChanges(before,after){const changes=[];function visit(a,b,path=[]){if(JSON.stringify(a)===JSON.stringify(b))return;if(isRecord(a)&&isRecord(b)){for(const key of new Set([...Object.keys(a),...Object.keys(b)]))visit(a[key],b[key],[...path,key]);}else changes.push({path:path.join(' › ')||'Definition',before:a,after:b});}visit(before,after);return changes;}
export function reviewProposal(before,after){requireThat(isRecord(after)&&after.id===before.id&&after.kind===before.kind&&after.schema===before.schema,'A proposal cannot change the definition identity or format.');const errors=validateContent(after);return{draft:clone(after),errors,changes:proposalChanges(before,after)};}
