import {FolderBackup} from '../storage/folder-backup.mjs';
import {download} from '../core/util.mjs';
import {$,esc,button,modal,toast,onError,formatDate} from './dom.mjs';
export async function installBackups(app){if(app.backup)return app.backup;app.backup=await new FolderBackup(app.repo,{notify:status=>{if(status.state==='error'||status.state==='permission-needed')toast(status.message,true);}}).init();app.scheduleBackup=()=>app.backup.schedule();return app.backup;}
export async function backupDialog(app){const backup=await installBackups(app),supported=typeof globalThis.showDirectoryPicker==='function';const d=modal('Backups you own','',{wide:true,subtitle:'Browser storage should not be your only copy.',footer:button('backup-export','Download complete archive','download')+button('backup-choose','Choose backup folder','folder','primary',supported?'':'disabled')+button('backup-now','Back up now','save')+button('backup-disconnect','Disconnect folder','close')});
  const render=()=>{const s=backup.status;d.body.innerHTML=`<div class="eyebrow">${esc(s.state.replaceAll('-',' '))}</div><h3>${s.lastSuccess?'Last verified backup: '+formatDate(s.lastSuccess):'No folder backup verified yet'}</h3><p>${esc(s.message || 'Choose a folder, or download a complete portable archive.')}</p>${s.filename?`<p class="editor-help">File: ${esc(s.filename)}<br>SHA-256: <code>${esc(s.hash)}</code></p>`:''}<div class="notice info">${supported?'Choose a folder you control. EA3 writes into its own EmberAdventures3-backups subfolder and alternates two complete copies. Writes are read back and verified. It never silently asks for folder permission in the background.':'This browser does not expose folder access. Complete portable archives are available here and can be saved with the browser’s download or share controls.'}</div><p class="editor-help">Folder backup runs after adventure changes while the application is open. An interrupted write retains the previous verified slot. Disconnection does not delete files. Use a complete archive to move between browsers or devices.</p><a class="button" href="/recovery.html" target="_blank" rel="noopener">Independent emergency recovery</a>`;$('[data-action="backup-now"]',d.element).disabled=!backup.enabled;$('[data-action="backup-disconnect"]',d.element).disabled=!backup.enabled;};
  const run=async fn=>{try{await fn();render();}catch(e){onError(e);render();}};
  d.on('click','[data-action="backup-choose"]',()=>run(async()=>{const handle=await showDirectoryPicker({mode:'readwrite',id:'emberadventures-backups'});await backup.connect(handle);}));
  d.on('click','[data-action="backup-now"]',()=>run(()=>backup.write({requestPermission:true})));
  d.on('click','[data-action="backup-disconnect"]',()=>run(()=>backup.disconnect()));
  d.on('click','[data-action="backup-export"]',()=>run(async()=>{download('EmberAdventures-complete-backup.ea3.json',await app.repo.exportArchive());toast('Complete archive prepared. Store it outside browser storage.');}));render();return d;
}
