import {importPublication} from '../community.mjs';
import {requireThat} from '../core/util.mjs';
import {communityClient,signInDialog} from './community-auth.mjs';
import {$,$$,esc,button,badge,image,field,modal,confirmDialog,empty,toast,onError,formatDate} from './dom.mjs';

export async function communityDialog(app){
 const client=communityClient(app);let info,tab='discover',page=0,epoch=0,closed=false,filters={q:'',kind:'',genre:'',creator:'',sort:'featured'},controller;
 const d=modal('Community Library','<p class="editor-help">Connecting to this community instance…</p>',{wide:true,klass:'community-dialog',subtitle:'Discover a story. Share something of your own.',onClose:()=>{closed=true;epoch++;controller?.abort();}});
 try{info=await client.session();}catch(error){d.body.innerHTML=empty('Community service unavailable',error.message+' Your local libraries and adventures are unchanged.');return d;}
 function shell(){d.body.innerHTML=`<header class="community-head"><div><div class="eyebrow">${esc(info.instance)}</div><small>Public here means visible to visitors of this server, not automatically to every EmberAdventures installation.</small></div><div class="row wrap">${client.user?badge(client.user.username)+button('community-logout','Sign out',null,'small'):button('community-login','Sign in','user','small')}</div></header><nav class="community-tabs" aria-label="Community sections">${[['discover','Discover'],['publish','Publish from library'],['mine','My publications'],['receipts','Pending operations']].map(([k,v])=>`<button type="button" class="editor-tab ${tab===k?'active':''}" data-community-tab="${k}">${v}</button>`).join('')}</nav><div id="community-panel"></div><p id="community-status" role="status"></p>`;}
 async function render(){const token=++epoch;controller?.abort();controller=new AbortController();shell();const panel=$('#community-panel',d.element);panel.innerHTML='<p class="editor-help">Loading…</p>';
  try{
   if(tab==='discover'){
    const params=new URLSearchParams({...filters,page,mode:app.profile.rating==='mature'?'mature':'sfw'});const data=await client.request('/api/public/items?'+params,{signal:controller.signal});if(closed||token!==epoch)return;
    panel.innerHTML=`<form id="community-filter" class="community-filters">${field('Search','q',filters.q,{type:'search',placeholder:'Name, creator or description'})}${field('Content','kind',filters.kind,{options:[['','All content'],['story','Stories'],['character','Characters']]})}${field('Genre','genre',filters.genre,{options:[['','All genres'],...data.genres]})}${field('Creator','creator',filters.creator,{options:[['','All creators'],...data.creators]})}${field('Sort','sort',filters.sort,{options:[['featured','Featured'],['recent','Newest'],['name','Name'],['rating','Rating']]})}<button type="submit" class="button">Search</button></form><div class="community-grid">${data.items.map(c=>`<article class="community-card"><button type="button" class="community-art" data-action="community-detail" data-version="${esc(c.versionId)}" aria-label="Open ${esc(c.title)}">${image(c.thumbnail || '/public/art/daylight.png',c.title,'','loading="lazy"')}</button><div class="community-card-body"><div class="row wrap">${badge(c.kind)}${c.featured?badge('Featured','warm'):''}${badge(c.rating==='sfw'?'SFW':'Mature')}</div><h3>${esc(c.title)}</h3><p>${esc(c.description)}</p><small>Created by ${esc(c.creator)}<br>Uploaded by ${esc(c.uploader)} · Version ${c.number}</small><div class="row between"><span class="muted">${c.ratings?Number(c.score).toFixed(1)+' / 5 · '+c.ratings+' ratings':'Not rated yet'}</span>${button('community-detail','View','arrow','small',`data-version="${esc(c.versionId)}"`)}</div></div></article>`).join('')||empty('Make room for the first story','Nothing matches these filters on this instance. Publish a library item, or try another search.')}</div><div class="page-footer"><span>${data.total} results</span><div class="row">${button('community-prev','Previous','back','small',page?'':'disabled')}<span>${page+1} / ${Math.max(1,Math.ceil(data.total/data.size))}</span>${button('community-next','Next','chevron','small',(page+1)*data.size<data.total?'':'disabled')}</div></div>`;
   }else if(tab==='publish'){
    const rows=await app.repo.listContent();if(closed||token!==epoch)return;
    panel.innerHTML=`<h3>Share selected library items</h3><p class="editor-help">Story publication includes its cast and referenced images. Existing adventures, profiles, passwords and conversation history are never published by this form. Only upload content you have the right to share.</p><form id="community-publish"><div class="community-publish-list">${rows.map(c=>`<label class="publish-row"><input type="checkbox" name="selection" value="${esc(c.kind+':'+c.id)}">${image(app.imageSource(c.image),c.title,'save-thumb')}<span><strong>${esc(c.title)}</strong><small>${esc(c.kind)} · ${esc(c.creator || 'Uncredited')} · ${esc(c.rating)}</small></span></label>`).join('')||empty('Your library is empty','Create or import content before publishing.')}</div><label class="checkbox-line"><input type="checkbox" name="hidePrevious"><span>When updating my own publication, hide only its immediately previous version.</span></label><div class="row wrap" style="margin-top:18px"><button type="submit" class="button primary">Review & publish selected</button><small>Publishing requires a community account.</small></div></form><div id="publish-results" role="status"></div>`;
   }else if(tab==='mine'){
    if(!client.user){panel.innerHTML=empty('Your publications','Sign in to inspect your versions and their visibility.',button('community-login','Sign in','user','primary'));return;}
    const data=await client.request('/api/mine',{signal:controller.signal});if(closed||token!==epoch)return;
    panel.innerHTML=`<h3>Your publication history</h3><div class="stack">${data.versions.map(v=>`<article class="list-row"><div class="grow"><h3>${esc(v.title)}</h3><p>Version ${v.number} · ${esc(v.status)}${v.locked?' · moderation locked':''}</p><small>${formatDate(v.createdAt)} · Created by ${esc(v.creator)}</small></div><div class="row wrap">${button('community-detail','Inspect','search','small',`data-version="${esc(v.versionId)}"`)}${button('community-visibility',v.status==='public'?'Hide':'Restore','eye','small',`data-item="${esc(v.itemId)}" data-version="${esc(v.versionId)}" data-status="${v.status==='public'?'hidden':'public'}" ${v.locked&&v.status!=='public'?'disabled':''}`)}</div></article>`).join('')||empty('Nothing published yet','Your versions will appear here after publication.')}</div>`;
   }else{
    const jobs=(await app.repo.all('jobs')).filter(j=>j.kind==='publication');if(closed||token!==epoch)return;
    panel.innerHTML=`<h3>Publication receipts</h3><p class="editor-help">A lost response does not mean publication failed. Check the saved operation before creating another version. Reconciliation never republishes content.</p>${jobs.map(j=>`<div class="list-row"><div class="grow"><strong>${esc(j.payload?.content?.title || j.payload?.content?.name || 'Publication')}</strong><p>${esc(j.state)} · ${esc(j.instance)}</p></div>${button('community-reconcile','Check receipt','refresh','small',`data-job="${esc(j.id)}"`)}</div>`).join('')||empty('No unresolved publications','Successful operations have been reconciled with your local library.')}`;
   }
  }catch(error){if(error.name!=='AbortError'&&!closed&&token===epoch)panel.innerHTML=empty('Unable to load this section',error.message);}
 }
 d.on('click','[data-community-tab]',(_e,t)=>{tab=t.dataset.communityTab;page=0;render().catch(onError);});
 d.on('submit','#community-filter',e=>{e.preventDefault();filters=Object.fromEntries(new FormData(e.target));page=0;render().catch(onError);});
 d.on('submit','#community-publish',async e=>{e.preventDefault();const selected=new FormData(e.target).getAll('selection'),hidePrevious=e.target.elements.hidePrevious.checked,submit=$('button[type="submit"]',e.target);try{
   requireThat(selected.length,'Select at least one library item.');if(!await signInDialog(client))return;
   if(!await confirmDialog('Publish selected content?',`${selected.length} library items will be made public on “${info.instance}”. Stories include their cast and owned images. Existing publications you do not own become attributed new copies.`,{confirm:'Publish '+selected.length+' items'}))return;
   submit.disabled=true;const results=[];
   for(const key of selected){const colon=key.indexOf(':'),c=await app.repo.getContent(key.slice(0,colon),key.slice(colon+1));try{requireThat(c,'This local item was removed.');const r=await client.publish(app.repo,c,{hidePrevious});results.push(`${c.title || c.name}: published version ${r.number}${r.warning?' · '+r.warning:''}`);}catch(error){results.push(`${c?.title || c?.name || key}: ${error.message}. Check Pending operations before retrying.`);}}
   $('#publish-results',d.element).textContent=results.join('\n');await app.refresh();app.scheduleBackup?.();
  }catch(error){onError(error);}finally{submit.disabled=false;}});
 const actions={
  'community-login':async()=>{if(await signInDialog(client))await render();},'community-logout':async()=>{await client.signOut();await render();},
  'community-prev':async()=>{page--;await render();},'community-next':async()=>{page++;await render();},
  'community-detail':t=>publicDetail(app,t.dataset.version),
  'community-reconcile':async t=>{if(!await signInDialog(client))return;const job=await app.repo.get('jobs',t.dataset.job);requireThat(job,'This operation is no longer pending.');const r=await client.reconcile(app.repo,job);toast(r.warning || 'Publication receipt verified.');await render();},
  'community-visibility':async t=>{if(!await confirmDialog('Change version visibility?',`Set this exact version to ${t.dataset.status}? Other versions remain unchanged.`,{confirm:'Change visibility'}))return;await client.request('/api/items/'+t.dataset.item+'/visibility',{method:'POST',body:{versionId:t.dataset.version,status:t.dataset.status}});await render();}
 };
 d.on('click','[data-action]',(_e,t)=>{const fn=actions[t.dataset.action];if(fn)Promise.resolve().then(()=>fn(t)).catch(onError);});await render();return d;
}
export async function publicDetail(app,versionId){
 const client=communityClient(app),bundle=await client.request('/api/versions/'+encodeURIComponent(versionId)),v=bundle.summary,c=bundle.content;
 requireThat(app.profile.rating==='mature'||v.rating==='sfw','This version uses mature classification. Select a compatible profile first.');
 const d=modal(v.title,`<div class="split"><section>${image(c.image || v.thumbnail,v.title,'detail-art')}<p class="detail-description">${esc(c.description)}</p><div class="tag-list">${(c.tags||[]).map(t=>badge(t)).join('')}</div></section><section><div class="eyebrow">${esc(v.genre || v.kind)}</div><h3>Version ${v.number}</h3><p>Created by <strong>${esc(v.creator)}</strong><br>Uploaded by ${esc(v.uploader)}</p><p class="editor-help">${c.kind==='story'?`${c.nodes.length} story moments · ${bundle.characters.length} included characters`:esc(c.personality)}</p>${badge(v.rating==='sfw'?'SFW':'Mature')}${badge(v.status)}<hr><p class="editor-help">Downloading creates a local editable copy. It retains this exact public version for feedback. Existing local items are not overwritten.</p>${button('public-download','Add to my library','download','primary wide')}</section></div>`,{wide:true,footer:button('public-feedback','Rate or report this version','flag')});
 d.on('click','[data-action="public-download"]',async(_e,t)=>{t.disabled=true;try{const r=await importPublication(app.repo,bundle,{instance:client.instance});await app.refresh();app.scheduleBackup?.();toast(r.duplicate?'This exact version is already in your library.':'Added to your library with its cast and images.');}catch(error){onError(error);}finally{t.disabled=false;}});
 d.on('click','[data-action="public-feedback"]',()=>feedbackDialog(app,{...v,instance:client.instance}).catch(onError));return d;
}
export async function feedbackDialog(app,reference){
 const client=communityClient(app);requireThat(!reference.instance||reference.instance===client.instance,'This content belongs to another community instance. Feedback was not sent to this server.');await client.session();if(!await signInDialog(client))return;
 const d=modal('Feedback on this version',`<p class="editor-help">Feedback references version <strong>${esc(reference.versionId)}</strong>, even when your local copy has been edited.</p><form id="rating-form" class="form-section"><h3>Your rating</h3>${field('Rating','score',5,{options:[[5,'5 — Excellent'],[4,'4 — Good'],[3,'3 — Mixed'],[2,'2 — Needs work'],[1,'1 — Poor']]})}${field('Review','comment','',{type:'textarea',rows:3,extra:'maxlength="2000"'})}<button type="submit" class="button primary">Save rating</button></form><form id="report-form" class="form-section"><h3>Report a problem</h3>${field('Reason','reason','broken',{options:[['broken','Broken content'],['classification','Incorrect classification'],['ownership','Ownership / attribution'],['unsafe','Unsafe content'],['spam','Spam'],['other','Other']]})}${field('Details','details','',{type:'textarea',rows:4,required:true,extra:'maxlength="8000"'})}${field('Reply email (optional)','contact','',{type:'email',help:'Visible only to the operator reviewing your report.'})}<p class="editor-help">This submits a report to this instance’s moderators. It does not send an email.</p><button type="submit" class="button">Submit report</button></form><p id="feedback-status" role="status"></p>`,{wide:true});
 for(const [selector,path,method]of [['#rating-form','/api/ratings','PUT'],['#report-form','/api/reports','POST']])d.on('submit',selector,async e=>{e.preventDefault();const b=$('button[type="submit"]',e.target);b.disabled=true;try{const data=Object.fromEntries(new FormData(e.target));if(data.score)data.score=Number(data.score);await client.request(path,{method,body:{...data,versionId:reference.versionId}});$('#feedback-status',d.element).textContent=path.endsWith('ratings')?'Rating saved.':'Report submitted for this exact version. No email was sent.';e.target.reset();}catch(error){onError(error);}finally{b.disabled=false;}});return d;
}
