import {clone,id,now,requireThat,canonical,download} from '../core/util.mjs';
import {makeImageProvider} from '../providers/registry.mjs';
import {readRaster,cropRaster,cropRect,dataBlob,removeUnusedAsset} from '../media/raster.mjs';
import {$,$$,esc,button,badge,image,field,modal,confirmDialog,readForm,toast,onError,empty} from './dom.mjs';
const owner=app=>app.session?'save:'+app.session.save.id:'library:images';
const subjects=app=>[['scene','Current scene'],...(app.session?.save.characters || []).map(c=>[c.id,c.name])];
async function store(app,raster,meta={}){const asset=await app.repo.putAsset({...raster,...meta,createdAt:now(),links:meta.links || {[owner(app)]:true}});await app.refreshAssets();return asset;}
export async function chooseFile(){return new Promise(resolve=>{const input=document.createElement('input');input.type='file';input.accept='image/png,image/jpeg,image/webp';input.hidden=true;document.body.append(input);input.onchange=()=>{const file=input.files[0];input.remove();resolve(file || null);};input.oncancel=()=>{input.remove();resolve(null);};input.click();});}
export async function gallery(app){
  let selected=null,favorites=false,subject='scene';const d=modal('Image Gallery','',{wide:true,klass:'gallery-dialog',subtitle:'Your images, with a clear choice of what appears in the adventure.',footer:button('gallery-upload','Upload image','upload')+button('gallery-generate','Generate image','spark')+button('gallery-favorites','Favorites only','heart')});
  async function render(){await app.refreshAssets();const all=[...app.assetCache.values()].filter(a=>!favorites||a.favorite).sort((a,b)=>(b.createdAt || '').localeCompare(a.createdAt || ''));if(!all.some(a=>a.id===selected))selected=all[0]?.id;const active=app.assetCache.get(selected);
    d.body.innerHTML=`<div class="gallery-layout"><section class="gallery-preview">${active?image(active.data,active.label || 'Selected gallery image','gallery-large'):`${empty('Make the scene your own','Upload an image or connect an image provider. Bundled story art stays separate from your owned gallery.')}`}<div class="gallery-caption">${active?`<strong>${esc(active.label || 'Your image')}</strong><small>${esc(active.provider || 'Upload')} · ${active.width || '?'} × ${active.height || '?'}</small>`:''}</div>${active?`<div class="row wrap">${button('gallery-favorite',active.favorite?'Unfavorite':'Favorite','heart','small')}${button('gallery-crop','Crop a copy','edit','small')}${button('gallery-download','Download','download','small')}${button('gallery-delete','Delete','trash','small danger')}</div>`:''}</section><section><div class="eyebrow">${all.length} owned images</div>${app.session&&active?`${field('Use image for','subject',subject,{options:subjects(app)})}${button('gallery-use','Use selected image','check','primary wide')}<p class="editor-help">Selection changes only when you confirm it here. It is never changed by an unrelated late generation.</p>`:''}<div class="gallery-grid">${all.map(a=>`<button type="button" class="gallery-thumb ${a.id===selected?'selected':''}" data-action="gallery-select" data-id="${esc(a.id)}" aria-label="Select ${esc(a.label || 'image')}" aria-pressed="${a.id===selected}">${image(a.data,a.label || 'Gallery image','','loading="lazy"')}<span>${esc(a.label || 'Your image')}${a.favorite?' ♥':''}</span></button>`).join('')}</div></section></div>`;
  }
  const actions={
    'gallery-select':async t=>{selected=t.dataset.id;await render();},'gallery-favorites':async()=>{favorites=!favorites;await render();},
    'gallery-upload':async()=>{const f=await chooseFile();if(!f)return;const a=await store(app,await readRaster(f),{label:f.name,provider:'upload'});selected=a.id;await render();toast(a.resized?'Uploaded a normalized copy (maximum edge 4096 px). Your original file is unchanged.':'Image uploaded. Choose where to use it.');},
    'gallery-use':async()=>{subject=$('[name="subject"]',d.element).value;await app.act({kind:'image',subject,assetId:selected});await app.refresh();toast('Selected image applied.');},
    'gallery-favorite':async()=>{const a=app.assetCache.get(selected);await app.repo.put('assets',a.id,{...a,favorite:!a.favorite});await render();},
    'gallery-download':()=>{const a=app.assetCache.get(selected);download('emberadventures-'+a.id.slice(0,20)+'.png',dataBlob(a.data));},
    'gallery-delete':async()=>{if(!await confirmDialog('Delete this image?','Unused images will be deleted. Images referenced by any adventure, history or library item are protected.',{confirm:'Delete unused image',danger:true}))return;await removeUnusedAsset(app.repo,selected);selected=null;await render();},
    'gallery-crop':()=>cropDialog(app,app.assetCache.get(selected),async a=>{selected=a.id;await render();}),
    'gallery-generate':()=>generateImageDialog(app,{onStored:async a=>{selected=a.id;await render();}})
  };
  d.on('click','[data-action]',(e,t)=>{if(actions[t.dataset.action])Promise.resolve().then(()=>actions[t.dataset.action](t)).catch(onError);});await render();return d;
}
export async function cropDialog(app,asset,onStored=()=>{}){
  const bitmap=await createImageBitmap(dataBlob(asset.data));const d=modal('Crop a copy',`<canvas class="crop-preview" aria-label="Crop preview"></canvas><div class="grid2">${field('Aspect ratio','ratio','original',{options:[['original','Original'],['1','Square'],['0.6666666667','Portrait 2:3'],['1.5','Landscape 3:2']]})}${field('Zoom','zoom',1,{type:'range',extra:'min="1" max="4" step="0.05"'})}${field('Horizontal focus','x',50,{type:'range',extra:'min="0" max="100"'})}${field('Vertical focus','y',50,{type:'range',extra:'min="0" max="100"'})}</div><p class="editor-help">A new image is created. The original and current selection are not changed.</p>`,{wide:true,footer:button('crop-save','Save cropped copy','check','primary'),onClose:()=>bitmap.close()});
  const options=()=>({ratio:$('[name="ratio"]',d.element).value==='original'?bitmap.width/bitmap.height:Number($('[name="ratio"]',d.element).value),zoom:Number($('[name="zoom"]',d.element).value),x:Number($('[name="x"]',d.element).value)/100,y:Number($('[name="y"]',d.element).value)/100});
  const draw=()=>{const canvas=$('canvas',d.element),scale=Math.min(1,760/bitmap.width,360/bitmap.height);canvas.width=bitmap.width*scale;canvas.height=bitmap.height*scale;const c=canvas.getContext('2d'),r=cropRect(bitmap.width,bitmap.height,options());c.drawImage(bitmap,0,0,canvas.width,canvas.height);c.fillStyle='#0009';c.fillRect(0,0,canvas.width,canvas.height);c.drawImage(bitmap,r.x,r.y,r.width,r.height,r.x*scale,r.y*scale,r.width*scale,r.height*scale);c.strokeStyle='#ffc185';c.lineWidth=2;c.strokeRect(r.x*scale,r.y*scale,r.width*scale,r.height*scale);};
  d.on('input','input,select',draw);d.on('change','select',draw);d.on('click','[data-action="crop-save"]',async(e,t)=>{t.disabled=true;try{const a=await store(app,await cropRaster(asset.data,options()),{label:(asset.label || 'Image')+' · crop',provider:'local crop',sourceAsset:asset.id});await onStored(a);d.close();toast('Cropped copy saved.');}catch(err){onError(err);t.disabled=false;}});draw();return d;
}
function generationRequest(app,subject,guidance){requireThat(app.session,'Start an adventure before generating a scene.');const save=app.session.save,c=save.characters.find(c=>c.id===subject),location=app.session.compiled.locations.get(save.state.location);return{requestId:id('image'),kind:c?'portrait':subject==='story'?'story':subject.startsWith('item:')?'item':subject.startsWith('location:')?'location':'scene',character:c?clone(c):undefined,subject:c?undefined:subject.startsWith('item:')?clone(app.session.compiled.items.get(subject.slice(5))):subject.startsWith('location:')?clone(app.session.compiled.locations.get(subject.slice(9))):{name:save.title,description:app.session.compiled.story.description},outfit:c?.wardrobe?.find(o=>o.id===save.state.outfits[c.id]),scene:{description:location?.description,text:save.events.filter(e=>e.narration).at(-1)?.narration},guidance,revision:save.revision};}
export async function generateImageDialog(app,{onStored=()=>{}}={}){
  let request=null,closed=false;const d=modal('Generate an image',`${field('Subject','subject','scene',{options:subjects(app)})}${field('Image direction','guidance','',{type:'textarea',rows:4,help:'Identity, clothing and current scene are included automatically.'})}<div id="image-progress" role="status" class="editor-help">An image provider must be configured. The local story demo does not generate images.</div><div id="image-result"></div>`,{wide:true,footer:button('image-request','Generate','spark','primary')+button('image-stop','Stop','stop'),onClose:()=>{closed=true;request?.abort();}});
  d.on('click','[data-action="image-stop"]',()=>request?.abort());d.on('click','[data-action="image-request"]',async(e,t)=>{let job;try{requireThat(!request,'An image request is already running.');const provider=makeImageProvider(app.settings),subject=$('[name="subject"]',d.element).value,req=generationRequest(app,subject,$('[name="guidance"]',d.element).value),saveId=app.session.save.id;job=req.requestId;request=new AbortController();t.disabled=true;$('#image-progress',d.element).textContent='Generating. The current image will stay selected.';await app.repo.put('jobs',job,{id:job,kind:'image',state:'submitted',provider:provider.id,request:req,createdAt:now()});
      const result=await provider.generate(req,{signal:request.signal});if(request.signal.aborted)throw new DOMException('Stopped','AbortError');const raster=await readRaster(dataBlob(result.data)),a=await store(app,raster,{label:subject==='scene'?'Scene image':subject,provider:result.provider || provider.id,model:result.model || '',sourceRevision:req.revision,links:{['save:'+saveId]:true}});await app.repo.remove('jobs',job);if(!closed){$('#image-result',d.element).innerHTML=image(a.data,'Generated image preview','gallery-large');$('#image-progress',d.element).textContent='Saved to your gallery. Select it there when ready.';await onStored(a);}
    }catch(err){if(job)await app.repo.put('jobs',job,{id:job,kind:'image',state:'failed-or-unknown',error:err.message,createdAt:now()});if(!closed)$('#image-progress',d.element).textContent=err.name==='AbortError'?'Stopped. The selected image is unchanged. Remote completion may be unknown.':err.message;onError(err);}finally{request=null;t.disabled=false;}});return d;
}
export async function appearanceDialog(app,character,{scope='adventure'}={}){
  const live=scope==='adventure';requireThat(!live||app.session,'Start an adventure first.');const baseRevision=live?app.session.save.revision:character.contentRevision,saveId=app.session?.save.id;
  let preview=null,stamp=null,epoch=0,request=null,closed=false;
  const initial={pronouns:character.pronouns || '',species:character.species || '',appearance:clone(character.appearance || {description:''})};
  const d=modal('Appearance & portrait',`<div class="appearance-layout"><section><div class="eyebrow">${esc(character.name)}</div>${field('Pronouns','pronouns',initial.pronouns)}${field('Species','species',initial.species)}${field('Visual description','description',initial.appearance.description || '',{type:'textarea',rows:5})}<div class="grid2">${['height','build','musculature','definition'].map(k=>field(k[0].toUpperCase()+k.slice(1)+' scale',k,initial.appearance[k] ?? 1,{type:'number',extra:'min="0" step="0.1"'})).join('')}</div><p class="editor-help">1 is a moderate artistic cue. Values can extend beyond ordinary proportions; finite nonnegative values are accepted. Actual results depend on the image provider.</p><div class="row wrap">${button('appearance-generate','Generate preview','spark')}${button('appearance-upload','Upload matching preview','upload')}</div></section><section><div id="appearance-preview">${image(app.imageSource(live?(app.session.save.state.images[character.id] || character.image):character.image),character.name,'gallery-large')}</div><p id="appearance-status" class="editor-help" role="status">Current portrait. Change settings, then generate or upload a matching preview before confirming.</p></section></div>`,{wide:true,footer:button('appearance-reset','Restore original','back')+button('appearance-confirm','Confirm appearance & portrait','check','primary','disabled'),onClose:()=>{closed=true;epoch++;request?.abort();}});
  const values=()=>{const p={pronouns:$('[name="pronouns"]',d.element).value,species:$('[name="species"]',d.element).value,appearance:{...initial.appearance,description:$('[name="description"]',d.element).value}};for(const k of ['height','build','musculature','definition']){p.appearance[k]=Number($(`[name="${k}"]`,d.element).value);requireThat(Number.isFinite(p.appearance[k])&&p.appearance[k]>=0,'Appearance scales must be finite nonnegative numbers.');}return p;};
  function invalidate(){epoch++;preview=null;stamp=null;request?.abort();$('[data-action="appearance-confirm"]',d.element).disabled=true;$('#appearance-status',d.element).textContent='Settings changed. A matching preview is needed.';}
  d.on('input','input,textarea',invalidate);
  async function accept(raster,p,e){if(closed||e!==epoch)return;preview=raster;stamp=canonical(p);$('#appearance-preview',d.element).innerHTML=image(raster.data,'Matching presentation preview','gallery-large');$('#appearance-status',d.element).textContent='Preview matches these settings. Inspect it, then confirm both together.';$('[data-action="appearance-confirm"]',d.element).disabled=false;}
  d.on('click','[data-action="appearance-upload"]',async()=>{try{const p=values(),e=++epoch,file=await chooseFile();if(file)await accept(await readRaster(file),p,e);}catch(err){onError(err);}});
  d.on('click','[data-action="appearance-generate"]',async(e,t)=>{try{const provider=makeImageProvider(app.settings),p=values(),stampEpoch=++epoch;request?.abort();request=new AbortController();t.disabled=true;$('#appearance-status',d.element).textContent='Generating a matching preview…';const c={...clone(character),...p},result=await provider.generate({requestId:id('portrait'),kind:'portrait',character:c,outfit:c.wardrobe?.find(o=>o.id===app.session?.save.state.outfits[c.id]),guidance:'Preserve this character’s recognizable identity.'},{signal:request.signal});if(request.signal.aborted)return;await accept(await readRaster(dataBlob(result.data)),p,stampEpoch);}catch(err){onError(err);if(!closed)$('#appearance-status',d.element).textContent=err.message;}finally{request=null;t.disabled=false;}});
  d.on('click','[data-action="appearance-confirm"]',async(e,t)=>{t.disabled=true;try{const p=values();requireThat(preview&&stamp===canonical(p),'The preview no longer matches these settings.');if(live)requireThat(app.session?.save.id===saveId&&app.session.save.revision===baseRevision,'The adventure changed. Close and reopen appearance to prepare a current preview.');const a=await store(app,preview,{label:character.name+' · portrait',provider:'reviewed preview',links:{[live?'save:'+saveId:'library:character:'+character.id]:true}});
      if(live)await app.act({kind:'presentation',characterId:character.id,presentation:p,assetId:a.id,expectedRevision:baseRevision});
      else await app.repo.putContent({...clone(character),...p,image:'asset:'+a.id,originalPresentation:character.originalPresentation || initial,originalImage:character.originalImage || character.image},{expectedRevision:baseRevision});
      await app.refresh();d.close();toast('Appearance and portrait applied together.');
    }catch(err){onError(err);t.disabled=false;}});
  d.on('click','[data-action="appearance-reset"]',async()=>{try{if(!await confirmDialog('Restore original appearance?','Restore the original character description and portrait for this context?',{confirm:'Restore original'}))return;if(live){requireThat(app.session?.save.id===saveId,'The active adventure changed.');await app.act({kind:'reset-presentation',characterId:character.id});}else{requireThat(character.originalPresentation,'This character already uses its original presentation.');await app.repo.putContent({...character,...character.originalPresentation,image:character.originalImage || ''},{expectedRevision:baseRevision});}await app.refresh();d.close();}catch(err){onError(err);}});return d;
}
