import {clone,id,now,download,safeJSON,requireThat} from '../core/util.mjs';
import {compile,validateContent} from '../core/schema.mjs';
import {availableOffers,meets} from '../core/runtime.mjs';
import {esc,$,$$,button,ibutton,badge,image,paragraphs,field,empty,modal,confirmDialog,readForm,formatDate,toast,onError,closeDialogs} from './dom.mjs';
import {icon} from './icons.mjs';
export async function contentDetail(app,kind,key){
  const c=await app.repo.getContent(kind,key);requireThat(c,'This item is no longer in your library.');const story=kind==='story';
  const d=modal(c.title || c.name,`<div class="split"><section>${image(app.imageSource(c.image),c.title || c.name,'detail-art')}<p class="detail-description" style="margin-top:20px">${esc(c.description)}</p><div class="tag-list">${(c.tags || []).map(t=>badge(t)).join('')}</div></section><section><div class="eyebrow">${esc(c.genre || c.role || 'Your library')}</div><div class="detail-stats">${story?`<div><strong>${c.nodes.length}</strong><span>Story moments</span></div><div><strong>${c.locations.length}</strong><span>Locations</span></div><div><strong>${c.cast?.length || 0}</strong><span>Characters</span></div>`:`<div><strong>${c.age}</strong><span>Age</span></div><div><strong>${esc(c.species || 'human')}</strong><span>Species</span></div><div><strong>${esc(c.pronouns || '—')}</strong><span>Pronouns</span></div>`}</div><h3>${story?'A story on your terms':'Meet the character'}</h3><p class="muted">${esc(story?(c.initiative==='npc'?'The characters take initiative. You can respond, observe, or set your own direction.':c.initiative==='player'?'Your choices lead the way. Take the initiative and explore at your own pace.':'Share the initiative with the world and its characters.'):c.personality)}</p>${!story?`<p class="muted" style="font-size:12px">${esc(c.speech || '')}</p>`:''}<small>Created by ${esc(c.creator || 'you')}<br>${c.rating==='sfw'?'SFW content':'Mature relationships'} · stored locally</small><hr><div class="stack" style="gap:9px">${button(story?'detail-begin':'detail-chat',story?'Begin this adventure':'Start a character adventure','play','primary wide')}${!story?button('detail-play-as','Play as this character','user','wide'):''}${!story && app.session?button('detail-add','Add to current adventure','users','wide'):''}${button('detail-edit',story?'Open story editor':'Edit character','edit','wide')}</div></section></div>`,{wide:true,footer:(c.public?button('detail-feedback','Rate / report public version','flag'):'')+button('detail-export','Export','download')+button('detail-copy','Duplicate','folder')+button('detail-delete','Delete','trash','danger')});
  d.on('click','[data-action="detail-begin"]',()=>{d.close();storySetup(app,c).catch(onError);});
  d.on('click','[data-action="detail-chat"]',()=>{d.close();characterStart(app,c).catch(onError);});
  d.on('click','[data-action="detail-play-as"]',async()=>{app.profile={...app.profile,name:c.name,description:c.description,pronouns:c.pronouns,characterId:c.id,appearance:clone(c.appearance)};await app.persistProfile();d.close();toast(`${c.name} is selected as your player identity for new adventures.`);});
  d.on('click','[data-action="detail-add"]',async()=>{try{requireThat(app.session.save.profile.rating==='mature'||c.rating!=='mature','This character is not compatible with the adventure profile.');requireThat(!app.session.save.characters.some(x=>x.id===c.id),'This character is already part of the adventure.');await app.addCharacter(c);d.close();toast(`${c.name} joined the scene.`);}catch(e){onError(e);}});
  d.on('click','[data-action="detail-edit"]',()=>{d.close();app.openEditor(kind,c).catch(onError);});
  d.on('click','[data-action="detail-feedback"]',async()=>{try{const {feedbackDialog}=await import('./community.mjs');await feedbackDialog(app,c.public);}catch(e){onError(e);}});
  d.on('click','[data-action="detail-export"]',()=>download(`${c.id}.ea3.json`,c));
  d.on('click','[data-action="detail-copy"]',async()=>{try{const copy={...clone(c),id:id(kind),...(story?{title:c.title+' · copy'}:{name:c.name+' · copy'})};delete copy.contentRevision;await app.repo.putContent(copy);d.close();await app.navigate(story?'stories':'characters');toast('A separate copy was added to your library.');}catch(e){onError(e);}});
  d.on('click','[data-action="detail-delete"]',async()=>{if(await confirmDialog('Delete from your library?',`Delete ${c.title || c.name}? Adventures already using this item retain their frozen copy.`,{confirm:'Delete item',danger:true})){await app.repo.removeContent(kind,c.id);d.close();await app.navigate(story?'stories':'characters');}});
}
export async function storySetup(app,story,{extraCharacters=[]}={}){
  const chars=await app.repo.listContent('character'),stored=await Promise.all(chars.map(c=>app.repo.getContent('character',c.id))),all=[...stored.filter(c=>!extraCharacters.some(e=>e.id===c.id)),...extraCharacters],cast=(story.cast || []).map(k=>all.find(c=>c.id===k));
  const opening=story.nodes.find(n=>n.id===story.start)?.text || '';
  const d=modal('Begin your adventure',`<form id="setup-form" class="stack"><div class="row" style="gap:16px">${image(app.imageSource(story.image),story.title,'save-thumb')}<div><div class="eyebrow" style="margin-bottom:5px">${esc(story.genre || 'Adventure')}</div><h3 style="margin:0">${esc(story.title)}</h3></div></div><div class="grid2">${field('Your name','name',app.profile.name,{required:true})}${field('Pronouns','pronouns',app.profile.pronouns || '',{placeholder:'Optional'})}</div>${field('Your character','description',app.profile.description || '',{type:'textarea',rows:2,placeholder:'Who are you in this world? A few details are enough.'})}${field('Adventure title','title',story.title,{required:true})}<details><summary class="muted" style="cursor:pointer;font-size:12px">Customize the opening</summary><div style="margin-top:12px">${field('Opening narration','opening',opening,{type:'textarea',rows:6,help:'Changes apply to this adventure only. The library story stays unchanged.'})}</div></details><div><small>Opening cast</small><div class="row wrap" style="margin-top:9px">${cast.map(c=>badge(c?.name || 'Missing character',c?'':'warm')).join('')}</div></div><div class="notice info">${app.settings.textProvider==='demo'?'The local demo plays authored choices and scripted responses. It is not a language model. Configure a live provider in Settings for open-ended AI conversation.':'The selected text provider will narrate your actions. Your story state and saves remain local.'}</div><p id="setup-error" class="inline-error" role="alert" hidden></p></form>`,{subtitle:'Choose who you are. The rest can unfold along the way.',footer:button('setup-cancel','Cancel',null)+`<button class="button primary" type="submit" form="setup-form">${icon('play')}Begin Adventure</button>`});
  d.on('click','[data-action="setup-cancel"]',()=>d.close());
  d.on('submit','#setup-form',async e=>{e.preventDefault();const data=readForm(e.target),submit=$('button[type=submit]',d.element);submit.disabled=true;try{const profile={...app.profile,name:data.name.trim(),pronouns:data.pronouns,description:data.description};await app.begin(story,all,profile,{title:data.title.trim(),opening:data.opening});d.close();}catch(err){const error=$('#setup-error',d.element);error.textContent=err.message;error.hidden=false;submit.disabled=false;}});
}
export async function characterStart(app,c){
  const story={schema:'ea3/1',kind:'story',id:id('character-story'),title:`An adventure with ${c.name}`,rating:c.rating,creator:c.creator,genre:'Character adventure',tags:['open-ended'],description:c.description,image:c.image,initiative:'shared',cast:[c.id],start:'opening',nodes:[{id:'opening',title:'A first meeting',text:c.opening || `${c.name} looks up, making room for the conversation to begin.`,location:'meeting',choices:[]}],locations:[{id:'meeting',name:'A place to begin',description:'The world is open to the story you build together.',links:[],discovered:true,cast:[c.id]}],initial:{resources:{gold:0}},items:[],offers:[],developments:[],rules:c.backstory || '',afterEnding:'freeplay'};
  return storySetup(app,story,{extraCharacters:[c]});
}
