import {inspectLegacy} from '../migration/convert.mjs';
import {clone,id,download,now} from '../core/util.mjs';
import {$,esc,button,field,modal,toast,onError,confirmDialog} from './dom.mjs';
export async function legacyImportDialog(app,data,{name,text}={}){
 const report=await inspectLegacy(data,{name,rawText:text});let page=0,preserved=false;
 const d=modal('Legacy import review','',{wide:true,subtitle:'Keep the original. Inspect what changes. Nothing is overwritten.',footer:button('migration-source','Save original locally','save')+button('migration-report','Download review report','download')+button('migration-original','Download original','download')});
 async function preserve(){if(preserved)return;await app.repo.put('quarantine','legacy:'+report.sourceHash,{kind:'original-import',name,rawText:text || JSON.stringify(data),hash:report.sourceHash,report:{...report,candidates:undefined},createdAt:now()});preserved=true;toast('Original retained locally, unchanged. Keep your own file copy too.');}
 function render(){const c=report.counts,items=report.issues.slice(page*30,(page+1)*30);d.body.innerHTML=`<div class="eyebrow">${esc(report.kind)}</div><h3>${esc(name || 'Imported file')}</h3><div class="detail-stats"><div><strong>${c.stories}</strong><span>Stories</span></div><div><strong>${c.characters}</strong><span>Characters</span></div><div><strong>${c.nodes.toLocaleString()}</strong><span>Graph nodes retained</span></div></div><p class="notice info">${c.blocked?'Some behavior cannot be reproduced automatically. Imported controls with unconverted conditions/effects are blocked by explicit review flags. Repair them in the editor; this is not a playable parity conversion.':'Review the converted content and playtest before saving it to your library.'}</p>${report.candidates.length?`${field('Review draft','candidate',report.candidates.find(c=>c.kind==='story')?.id || report.candidates[0].id,{options:report.candidates.map(c=>[c.id,(c.kind==='story'?'Story: ':'Character: ')+(c.title || c.name)])})}${button('migration-open','Keep original & open draft editor','edit','primary')}`:''}<h3 style="margin-top:22px">${c.issues.toLocaleString()} review findings</h3><div style="max-height:300px;overflow:auto">${items.map(i=>`<div class="list-row"><div><strong>${esc(i.path)}</strong><p>${esc(i.message)}</p></div></div>`).join('')||'<p>No structural issues found by this converter.</p>'}</div><div class="row between">${button('migration-prev','Previous',null,'small',page?'':'disabled')}<small>Page ${page+1} / ${Math.max(1,Math.ceil(c.issues/30))}</small>${button('migration-next','Next',null,'small',(page+1)*30<c.issues?'':'disabled')}</div>`;}
 d.on('click','[data-action]',(e,t)=>{const a=t.dataset.action;Promise.resolve().then(async()=>{if(a==='migration-prev'){page--;render();}if(a==='migration-next'){page++;render();}if(a==='migration-source')await preserve();if(a==='migration-report')download(name+'.migration-review.json',{...report,candidates:report.candidates.map(c=>({id:c.id,kind:c.kind,title:c.title || c.name}))});if(a==='migration-original')download(name || 'legacy-original.json',text || JSON.stringify(data),'application/json');if(a==='migration-open'){await preserve();const selected=clone(report.candidates.find(c=>c.id===$('[name="candidate"]',d.element).value));if(await app.repo.getContent(selected.kind,selected.id)){selected.id=id(selected.kind);delete selected.contentRevision;}d.close();await app.openEditor(selected.kind,selected);}}).catch(onError);});render();return d;
}
