import {clone,id,now,download,safeJSON,requireThat} from '../core/util.mjs';
import {compile,validateContent} from '../core/schema.mjs';
import {availableOffers,meets} from '../core/runtime.mjs';
import {esc,$,$$,button,ibutton,badge,image,paragraphs,field,empty,modal,confirmDialog,readForm,formatDate,toast,onError,closeDialogs} from './dom.mjs';
import {icon} from './icons.mjs';
import {dataTools} from './save-dialogs.mjs';
export async function profiles(app){
  const list=await app.repo.get('meta','profiles') || [app.profile];
  const d=modal('Player profiles',`<p class="muted" style="font-size:12px">Profiles keep your player identities and content preferences separate. Existing adventures keep the profile they started with.</p><div class="stack">${list.map(p=>`<div class="list-row"><span class="mini-avatar">${esc(p.name[0])}</span><div class="grow"><h3>${esc(p.name)}</h3><p>${p.rating==='mature'?'Mature relationships':'SFW'}${p.id===app.profile.id?' · active':''}</p></div>${button('select-profile','Select','check','small',`data-id="${esc(p.id)}"`)}${ibutton('edit-profile','Edit profile','edit',`data-id="${esc(p.id)}"`)}${list.length>1?ibutton('delete-profile','Delete profile','trash',`data-id="${esc(p.id)}"`):''}</div>`).join('')}</div>`,{footer:button('new-profile','New profile','plus','primary')});
  const edit=profile=>{const p=profile || {id:id('profile'),name:'Traveler',rating:'sfw',description:'',pronouns:''};const form=modal(profile?'Edit profile':'New profile',`<form id="profile-form" class="stack">${field('Name','name',p.name,{required:true})}${field('Pronouns','pronouns',p.pronouns || '')}${field('Player description','description',p.description || '',{type:'textarea'})}${field('Content mode','rating',p.rating,{options:[['sfw','SFW'],['mature','Mature relationships (non-explicit)']]})}<small>All player identities and characters are adults. This build does not include explicit sexual content or physical stimulation controls.</small></form>`,{footer:`<button class="button primary" type="submit" form="profile-form">${icon('save')}Save profile</button>`});form.on('submit','#profile-form',async e=>{e.preventDefault();try{const data=readForm(e.target);const next={...p,...data,name:data.name.trim()};requireThat(next.name,'A profile needs a name.');const profiles=[...list.filter(x=>x.id!==p.id),next];await app.repo.put('meta','profiles',profiles);if(!profile || app.profile.id===p.id){app.profile=next;await app.repo.put('meta','activeProfile',p.id);}form.close();d.close();await app.refresh();profilesDialogAgain();}catch(err){onError(err);}});};
  const profilesDialogAgain=()=>profiles(app).catch(onError);
  d.on('click','[data-action="new-profile"]',()=>edit());d.on('click','[data-action="edit-profile"]',(_e,t)=>edit(list.find(p=>p.id===t.dataset.id)));
  d.on('click','[data-action="select-profile"]',async(_e,t)=>{app.profile=list.find(p=>p.id===t.dataset.id);await app.repo.put('meta','activeProfile',app.profile.id);d.close();await app.refresh();toast('Profile selected for new adventures.');});
  d.on('click','[data-action="delete-profile"]',async(_e,t)=>{if(await confirmDialog('Delete this profile?','Existing adventures keep their own identity. Only this reusable profile will be removed.',{confirm:'Delete profile',danger:true})){const next=list.filter(p=>p.id!==t.dataset.id);await app.repo.put('meta','profiles',next);if(app.profile.id===t.dataset.id){app.profile=next[0];await app.repo.put('meta','activeProfile',app.profile.id);}d.close();await app.refresh();profilesDialogAgain();}});
}
export async function settings(app){
  const s=app.settings;
  const d=modal('Settings',`<form id="settings-form" class="stack"><section class="form-section"><h3>Story & narration</h3><div class="grid2">${field('Text provider','textProvider',s.textProvider,{options:[['demo','Local story demo (not an AI)'],['http','Configured server provider'],['perchance','Perchance host bridge']]})}${field('Image provider','imageProvider',s.imageProvider || 'upload',{options:[['upload','Upload / existing images'],['http','Configured server image provider'],['perchance','Perchance host bridge']]})}</div><p class="muted" style="font-size:11px;margin:13px 0 0">Provider credentials belong in the local server’s environment, never in browser settings or exported saves.</p>${field('Narrative guidance','guidance',s.guidance || '',{type:'textarea',rows:2,placeholder:'Tone, pacing, and things the narrator should remember.'})}</section><section class="form-section"><h3>Reading & appearance</h3><div class="grid2">${field('Story text size','storySize',s.storySize || 16,{type:'number',extra:'min="13" max="26" step="1"'})}${field('Story typeface','storyFont',s.storyFont || 'sans',{options:[['sans','Clean sans-serif'],['serif','Classic serif']]})}</div><label class="checkbox-line" style="margin-top:16px"><input name="reduceMotion" type="checkbox" ${s.reduceMotion?'checked':''}><span>Reduce animation and transitions</span></label><label class="checkbox-line" style="margin-top:12px"><input name="voiceAuto" type="checkbox" ${s.voiceAuto?'checked':''}><span>Read new narration aloud (browser voices)</span></label></section><section class="form-section"><h3>Auto behavior</h3><div class="grid2">${field('Auto mode','autoMode',s.autoMode || 'observe',{options:[['observe','Observe — do not make my decisions'],['delegate','Delegate — allow marked safe choices']]})}${field('Turn budget','autoLimit',s.autoLimit || 4,{type:'number',extra:'min="1" max="100"'})}</div><small style="display:block;margin-top:12px">Auto always has a visible Stop control. Observe pauses when the story needs your decision. Delegate only selects choices the author explicitly marked safe for Auto.</small></section><div class="row wrap">${button('settings-backups','Backups & recovery','folder')}${button('settings-profiles','Player profiles','user')}${button('settings-provider-status','Check provider connection','link')}</div><p id="settings-error" class="inline-error" hidden role="alert"></p></form>`,{wide:true,subtitle:'Keep the adventure comfortable. Keep your data yours.',footer:button('settings-cancel','Cancel',null)+`<button type="submit" form="settings-form" class="button primary">${icon('check')}Save settings</button>`});
  d.on('click','[data-action="settings-cancel"]',()=>d.close());d.on('click','[data-action="settings-backups"]',()=>dataTools(app));d.on('click','[data-action="settings-profiles"]',()=>profiles(app));
  d.on('click','[data-action="settings-provider-status"]',async()=>{try{const response=await fetch('/api/providers');if(!response.ok)throw new Error('Local provider service unavailable.');const info=await response.json();modal('Provider connections',`<div class="code-block">${esc(JSON.stringify(info,null,2))}</div>`);}catch(e){onError(e);}});
  d.on('submit','#settings-form',async e=>{e.preventDefault();const data=readForm(e.target);try{const next={...s,...data,storySize:Number(data.storySize),autoLimit:Number(data.autoLimit),voiceAuto:e.target.elements.voiceAuto.checked,reduceMotion:e.target.elements.reduceMotion.checked};requireThat(next.storySize>=13&&next.storySize<=26,'Text size must be 13–26.');requireThat(Number.isInteger(next.autoLimit)&&next.autoLimit>=1&&next.autoLimit<=100,'Auto budget must be 1–100.');app.session?.stop();await app.saveSettings(next);d.close();await app.refresh();toast('Settings saved.');}catch(err){const el=$('#settings-error',d.element);el.textContent=err.message;el.hidden=false;}});
}
export function autoSettings(app){
  const d=modal('Auto, on your terms',`<form id="auto-form" class="stack">${field('Mode','autoMode',app.settings.autoMode || 'observe',{options:[['observe','Observe — the world advances, you decide'],['delegate','Delegate — safe authored choices may be selected']]})}${field('Maximum turns','autoLimit',app.settings.autoLimit || 4,{type:'number',extra:'min="1" max="100"'})}<div class="notice info">Continue and Observe never invent a player message. Delegate does not give the narrator unrestricted control of your character.</div></form>`,{footer:`<button class="button primary" type="submit" form="auto-form">Save Auto settings</button>`});d.on('submit','#auto-form',async e=>{e.preventDefault();const data=readForm(e.target);try{requireThat(Number.isInteger(+data.autoLimit)&&+data.autoLimit>=1&&+data.autoLimit<=100,'Choose 1–100 turns.');await app.saveSettings({...app.settings,autoMode:data.autoMode,autoLimit:+data.autoLimit});d.close();}catch(err){onError(err);}});
}
