import {clone,id,now,download,safeJSON,requireThat} from '../core/util.mjs';
import {compile,validateContent} from '../core/schema.mjs';
import {availableOffers,meets} from '../core/runtime.mjs';
import {esc,$,$$,button,ibutton,badge,image,paragraphs,field,empty,modal,confirmDialog,readForm,formatDate,toast,onError,closeDialogs} from './dom.mjs';
import {icon} from './icons.mjs';
export async function saves(app){
  const list=await app.repo.listSaves();
  const d=modal('Your adventures',`<div class="stack">${list.map(s=>`<div class="list-row">${image('/public/art/landscape.png','','save-thumb')}<div class="grow"><h3>${esc(s.title)}</h3><p>${esc(s.profile?.name || 'Traveler')} · ${s.eventCount} story events</p><small>${formatDate(s.updatedAt)}${app.session?.save.id===s.id?' · current adventure':''}</small></div><div class="actions">${button('load-save','Load','play','small',`data-id="${esc(s.id)}"`)}${button('export-save','Export','download','small',`data-id="${esc(s.id)}"`)}${ibutton('rename-save','Rename adventure','edit',`data-id="${esc(s.id)}"`)}${ibutton('delete-save','Delete adventure','trash',`data-id="${esc(s.id)}"`)}</div></div>`).join('') || empty('The first page is still ahead','Begin an adventure. Every completed turn is saved automatically.')}</div><div class="notice info" style="margin-top:20px">Browser storage is not a backup. Export complete archives or enable folder backups to keep another copy of your adventures.</div>`,{wide:true,footer:button('import-save','Import archive','upload')+(app.session?button('copy-save','Save a separate copy','save'):'')+button('all-backups','Backups & recovery','folder')});
  d.on('click','[data-action="load-save"]',async(_e,t)=>{try{await app.loadSave(t.dataset.id);d.close();}catch(e){onError(e);}});
  d.on('click','[data-action="export-save"]',async(_e,t)=>{try{download(`adventure-${t.dataset.id}.ea3.json`,await app.repo.exportArchive({saveId:t.dataset.id}));toast('Complete adventure archive prepared.');}catch(e){onError(e);}});
  d.on('click','[data-action="copy-save"]',async()=>{try{await app.repo.copySave(app.session.save);d.close();await app.refreshSaves();saves(app);}catch(e){onError(e);}});
  d.on('click','[data-action="delete-save"]',async(_e,t)=>{if(await confirmDialog('Delete this adventure?','Its canonical history will be removed from this device. Export it first to keep a copy.',{confirm:'Delete adventure',danger:true})){if(app.session?.save.id===t.dataset.id){app.session.stop();app.session=null;await app.repo.remove('meta','activeSave');}await app.repo.removeSave(t.dataset.id);d.close();await app.navigate('home');saves(app);}});
  d.on('click','[data-action="rename-save"]',async(_e,t)=>{const save=await app.repo.readSave(t.dataset.id),form=modal('Rename adventure',`<form id="rename-form">${field('Title','title',save.title,{required:true})}</form>`,{footer:'<button class="button primary" type="submit" form="rename-form">Save title</button>'});form.on('submit','#rename-form',async e=>{e.preventDefault();try{const title=readForm(e.target).title.trim();requireThat(title,'A title is required.');if(app.session?.save.id===save.id)await app.session.updateMetadata({title});else await app.repo.commitSave({...save,title,revision:save.revision+1,updatedAt:now()},save.revision,{from:save.events.length});form.close();d.close();await app.refreshSaves();saves(app);}catch(err){onError(err);}});});
  d.on('click','[data-action="import-save"]',()=>app.pickImport());d.on('click','[data-action="all-backups"]',()=>dataTools(app));
}
export function bookmarks(app){
  requireThat(app.session,'Begin or load an adventure first.');const save=app.session.save;
  const d=modal('Story checkpoints',`<p class="muted" style="font-size:12px">A checkpoint marks a place in your current story. Returning to it replaces everything after that point; it does not create an alternate timeline.</p><div class="stack">${(save.bookmarks || []).map(b=>`<div class="list-row"><div class="grow"><h3>${esc(b.name)}</h3><small>${b.eventCount} story events · ${formatDate(b.at)}</small></div>${button('restore-checkpoint','Return here','refresh','small',`data-id="${esc(b.id)}"`)}${ibutton('remove-checkpoint','Remove marker','trash',`data-id="${esc(b.id)}"`)}</div>`).join('') || empty('Mark a moment worth keeping','You can return to this point later, restoring the story and its associated world state.')}</div><form id="bookmark-form" class="row" style="margin-top:22px">${field('Checkpoint name','name','',{required:true,placeholder:'Before taking the western road'})}<button class="button primary" type="submit" style="align-self:flex-end">${icon('plus')}Mark here</button></form>`);
  d.on('submit','#bookmark-form',async e=>{e.preventDefault();try{const name=readForm(e.target).name.trim();requireThat(name,'Name this checkpoint.');await app.session.updateMetadata({bookmarks:[...(app.session.save.bookmarks || []),{id:id('checkpoint'),name,eventCount:app.session.save.events.length,at:now()}]});d.close();bookmarks(app);}catch(err){onError(err);}});
  d.on('click','[data-action="restore-checkpoint"]',async(_e,t)=>{const b=app.session.save.bookmarks.find(x=>x.id===t.dataset.id);if(b && await confirmDialog('Return to this checkpoint?',`Everything after “${b.name}” will be removed from the current story, including associated world changes.`,{confirm:'Replace later history',danger:true})){await app.session.rewind(b.eventCount);d.close();}});
  d.on('click','[data-action="remove-checkpoint"]',async(_e,t)=>{await app.session.updateMetadata({bookmarks:app.session.save.bookmarks.filter(b=>b.id!==t.dataset.id)});d.close();bookmarks(app);});
}
export function editTurn(app,index){
  const e=app.session?.save.events[index];requireThat(e,'Choose an existing story turn.');
  const d=modal('Rewrite this moment',`<div class="notice" style="margin-bottom:18px">This replaces the current timeline from this moment onward. Later turns and their world changes are discarded only after the replacement saves successfully.</div><form id="rewrite-form" class="stack">${field('What to change','mode',e.playerText?'player':'narrator',{options:[...(e.playerText?[['player','My response — generate a new continuation']]:[]),['narrator','Narration — replace with my text']]})}${field('Replacement text','text',e.playerText || e.narration,{type:'textarea',rows:8,required:true})}<p class="inline-error" id="rewrite-error" hidden></p></form>`,{wide:true,footer:button('rewrite-cancel','Cancel',null)+`<button class="button primary" type="submit" form="rewrite-form">${icon('refresh')}Replace from here</button>`});
  d.on('change','select[name=mode]',(_e,t)=>{$('textarea[name=text]',d.element).value=t.value==='player'?e.playerText:e.narration;});d.on('click','[data-action="rewrite-cancel"]',()=>d.close());
  d.on('submit','#rewrite-form',async ev=>{ev.preventDefault();const data=readForm(ev.target);d.close();try{if(data.mode==='player')await app.session.edit(index,data.text);else await app.session.replaceNarration(index,data.text);}catch(err){onError(err);}});
}
export function guidance(app){
  const d=modal('Narrative guidance',`<form id="guidance-form" class="stack">${field('Guide the narrator','guidance',app.settings.guidance || '',{type:'textarea',rows:5,placeholder:'Keep the pace unhurried. Let characters take initiative. Focus on exploration…'})}<div class="notice info">This steers future narration. It does not change your inventory, rewrite your past decisions, or silently edit the authored story.</div></form>`,{footer:`<button class="button primary" type="submit" form="guidance-form">Save guidance</button>`});d.on('submit','#guidance-form',async e=>{e.preventDefault();await app.saveSettings({...app.settings,guidance:readForm(e.target).guidance});d.close();toast('Narrative guidance saved.');});
}
export async function dataTools(app){
  const saves=await app.repo.listSaves(),items=await app.repo.listContent();
  const d=modal('Your data, your control',`<div class="detail-stats"><div><strong>${saves.length}</strong><span>Adventures</span></div><div><strong>${items.length}</strong><span>Library items</span></div><div><strong>Local</strong><span>Storage</span></div></div><div class="stack">${button('export-everything','Export complete archive','download','primary wide')}${button('import-everything','Import a complete archive','upload','wide')}${button('folder-backup','Folder backups','folder','wide')}${button('send-adventure','Send adventure to another device','link','wide')}<a class="button" href="/recovery.html" target="_blank" rel="noopener">${icon('shield')}Independent recovery page</a></div><div class="notice info" style="margin-top:20px">Complete archives include stories, characters, saved history, and owned images. Imports are checked before any write. Conflicting adventures become separate copies, never silent overwrites.</div>`,{subtitle:'Keep a copy somewhere you own.'});
  d.on('click','[data-action="export-everything"]',async()=>{try{download(`EmberAdventures-backup-${new Date().toISOString().slice(0,10)}.ea3.json`,await app.repo.exportArchive());toast('Complete archive prepared. Keep it somewhere outside browser storage.');}catch(e){onError(e);}});d.on('click','[data-action="import-everything"]',()=>app.pickImport());d.on('click','[data-action="folder-backup"]',()=>app.backupDialog());d.on('click','[data-action="send-adventure"]',()=>app.transferDialog());
}
export function about(){modal('EmberAdventures, rebuilt',`<div class="eyebrow">The same fire. A better foundation.</div><h3>A familiar adventure, not a different game.</h3><p class="muted">The ember-and-black interface follows the original EmberAdventures: familiar libraries, a central conversation, character information on the left, and images on the right.</p><p class="muted">Underneath, story changes are transactional. Editing replaces unwanted history. Portable archives, reviewable memories, and independent recovery keep your work yours.</p><div class="notice info">The default local narrator is a labeled demonstration, not a language model. Configure a provider for live AI. Native browser and external integrations have their own acceptance status in the release report.</div>`);}
