import {prepareTransfer,TransferSender,TransferReceiver} from '../transfer-core.mjs';
import {safeJSON,requireThat,download,now,hash} from '../core/util.mjs';
import {$,button,field,modal,confirmDialog,toast,onError,esc} from './dom.mjs';
async function gather(peer){if(peer.iceGatheringState==='complete')return;await new Promise((resolve,reject)=>{const finish=()=>{clearTimeout(timer);peer.removeEventListener('icegatheringstatechange',changed);resolve();},changed=()=>{if(peer.iceGatheringState==='complete')finish();},timer=setTimeout(()=>{peer.removeEventListener('icegatheringstatechange',changed);reject(new Error('Local connection gathering timed out. Try again or use a portable archive.'));},10000);peer.addEventListener('icegatheringstatechange',changed);});}
function decode(text,type){requireThat(typeof text==='string'&&text.length<256000,'Pairing message is too large.');const data=safeJSON(text);requireThat(data.schema==='ea3/pair/1'&&data.description?.type===type&&typeof data.description.sdp==='string','This is not the expected EA3 pairing message.');return data.description;}
export async function transferDialog(app){
  const supported=typeof globalThis.RTCPeerConnection==='function';let peer=null,channel=null,protocol=null,closed=false;
  const d=modal('Send to my other device',`<p class="editor-help">Both devices must remain open. Direct handoff uses a manually paired WebRTC data channel with no discovery server, STUN service, TURN relay or cloud-save storage. It works only when the devices can connect directly. Portable archives are the fallback.</p><div class="grid2"><section><h3>1 · Sending device</h3><p class="editor-help">Open an adventure, create a pairing message, and copy it to your other device.</p>${button('transfer-offer','Create sending message','send','primary',supported&&app.session?'':'disabled')}</section><section><h3>2 · Receiving device</h3><p class="editor-help">Paste the sender’s message below and create a reply.</p>${button('transfer-answer','Create receiving reply','link','',supported?'':'disabled')}</section></div>${field('Pairing message from the other device','remote','',{type:'textarea',rows:4,help:'Share these connection details only with a device you control.'})}${button('transfer-connect','Sender: apply receiving reply','check')}${field('Your pairing message to copy','local','',{type:'textarea',rows:4,extra:'readonly'})}<div class="row wrap">${button('transfer-copy','Copy pairing message','folder')}${button('transfer-cancel','Disconnect','stop','danger')}</div><p id="transfer-status" role="status">${supported?'Ready to pair. Sending copy is always retained.':'Direct data channels are unavailable. Use a portable archive instead.'}</p><hr><h3>Portable-file alternative</h3><p class="editor-help">Download the current adventure, move the complete file with your own transfer method, and import it on the other device. All necessary owned images are included.</p>`,{wide:true,footer:button('transfer-file','Download current adventure','download','',app.session?'':'disabled')+button('transfer-import','Import an archive','upload'),onClose:()=>{closed=true;disconnect();}});
  const status=t=>{if(!closed)$('#transfer-status',d.element).textContent=t;};
  function disconnect(){protocol?.close();protocol=null;channel?.close();channel=null;peer?.close();peer=null;status('Disconnected. The source copy and unfinished received chunks are retained.');}
  function newPeer(){disconnect();peer=new RTCPeerConnection({iceServers:[]});peer.onconnectionstatechange=()=>{if(peer?.connectionState==='failed')status('Direct connection failed. Use a complete portable archive; no relay was silently used.');};return peer;}
  const key=manifest=>'transfer:'+manifest.id;
  const receiver=ch=>{channel=ch;protocol=new TransferReceiver(ch,{approve:async manifest=>{return confirmDialog('Receive this adventure?',`${manifest.title} · ${(manifest.bytes/1024/1024).toFixed(1)} MiB. Only accept a transfer you requested. Existing adventures will not be overwritten.`,{confirm:'Receive verified archive'});},load:async manifest=>{const saved=await app.repo.get('drafts',key(manifest)+':manifest');if(saved)requireThat(saved.manifest.hash===manifest.hash,'A saved transfer with this ID has a different digest.');return(await app.repo.all('drafts')).filter(r=>r.transferId===manifest.id&&r.type==='chunk');},persist:async record=>{if(record.type==='manifest')await app.repo.put('drafts',key(record.manifest)+':manifest',record);else await app.repo.put('drafts','transfer:'+record.id+':'+(record.type==='chunk'?record.index:'complete'),{...record,transferId:record.id,updatedAt:now()});},importArchive:a=>app.repo.importArchive(a),onProgress:status,onComplete:async result=>{status(result.duplicate?'This archive was already received.':'Transfer verified and imported. Open Saves to continue it.');await app.refresh();},onError:e=>{status(e.message);onError(e);}});};
  async function offer(){requireThat(app.session,'Open an adventure first.');const save=app.session.save,outgoing='transfer:outgoing:'+save.id,prior=await app.repo.get('drafts',outgoing);let prepared,archive;
    if(prior&&await confirmDialog('Resume the last outgoing snapshot?','Resume the already-prepared snapshot, or cancel this prompt to prepare a new snapshot of the current adventure.',{confirm:'Resume saved snapshot'})){archive=prior.archive;prepared=await prepareTransfer(archive,{id:prior.manifest.id,title:prior.manifest.title});requireThat(prepared.manifest.hash===prior.manifest.hash,'Outgoing snapshot was altered.');}
    else{archive=await app.repo.exportArchive({saveId:save.id});prepared=await prepareTransfer(archive,{title:save.title});await app.repo.put('drafts',outgoing,{manifest:prepared.manifest,archive,updatedAt:now()});}
    const p=newPeer();channel=p.createDataChannel('ea3-adventure',{ordered:true});channel.bufferedAmountLowThreshold=65536;channel.onopen=()=>{protocol=new TransferSender(channel,prepared,{onProgress:status,onComplete:()=>status('Transfer acknowledged. Your original adventure remains on this device.'),onError:e=>{status(e.message);onError(e);}});protocol.offer();};await p.setLocalDescription(await p.createOffer());await gather(p);$('#local',d.element);$('[name="local"]',d.element).value=JSON.stringify({schema:'ea3/pair/1',description:p.localDescription});status('Copy your sending message to the receiving device, then paste its reply here.');
  }
  async function answer(){const description=decode($('[name="remote"]',d.element).value,'offer'),p=newPeer();p.ondatachannel=e=>receiver(e.channel);await p.setRemoteDescription(description);await p.setLocalDescription(await p.createAnswer());await gather(p);$('[name="local"]',d.element).value=JSON.stringify({schema:'ea3/pair/1',description:p.localDescription});status('Copy this receiving reply back to the sending device. You will be asked before importing the archive.');}
  const actions={'transfer-offer':offer,'transfer-answer':answer,'transfer-connect':async()=>{requireThat(peer,'Create a sending message first.');await peer.setRemoteDescription(decode($('[name="remote"]',d.element).value,'answer'));status('Connecting directly…');},'transfer-cancel':disconnect,'transfer-copy':async()=>{const input=$('[name="local"]',d.element);input.select();try{await navigator.clipboard.writeText(input.value);toast('Pairing message copied.');}catch{toast('The message is selected. Copy it using your browser.');}},'transfer-file':async()=>{requireThat(app.session,'Open an adventure first.');download('EmberAdventures-handoff.ea3.json',await app.repo.exportArchive({saveId:app.session.save.id}));},'transfer-import':()=>app.pickImport()};
  d.on('click','[data-action]',(e,t)=>{const fn=actions[t.dataset.action];if(fn)Promise.resolve().then(fn).catch(err=>{status(err.message);onError(err);});});return d;
}
