import {memoryAssistant} from './memory-assistant.mjs';
import {clone,id,now,download,safeJSON,requireThat} from '../core/util.mjs';
import {compile,validateContent} from '../core/schema.mjs';
import {availableOffers,meets} from '../core/runtime.mjs';
import {esc,$,$$,button,ibutton,badge,image,paragraphs,field,empty,modal,confirmDialog,readForm,formatDate,toast,onError,closeDialogs} from './dom.mjs';
import {icon} from './icons.mjs';
export function cast(app){
  requireThat(app.session,'Begin or load an adventure first.');const s=app.session.save;
  const d=modal('Characters',`<div class="stack">${s.characters.map(c=>`<div class="list-row">${image(app.imageSource(s.state.images[c.id] || c.image),c.name,'character-avatar')}<div class="grow"><h3>${esc(c.name)}</h3><p>${esc(c.role || c.species || '')}</p><div class="row" style="margin-top:6px">${badge(s.state.present.includes(c.id)?'In this scene':'Elsewhere')}${s.state.party.includes(c.id)?badge('In your party','warm'):''}</div></div>${button('cast-inspect','View','chevron','small',`data-id="${esc(c.id)}"`)}</div>`).join('')}</div>`,{footer:button('cast-library','Open character library','users')});d.on('click','[data-action="cast-inspect"]',(_e,t)=>inspectCharacter(app,t.dataset.id));d.on('click','[data-action="cast-library"]',()=>{d.close();app.navigate('characters');});
}
export function inspectCharacter(app,key){
  const save=app.session?.save,c=save?.characters.find(x=>x.id===key);requireThat(c,'This character is not in the current adventure.');const state=save.state;
  const d=modal(c.name,`<div class="split"><div>${image(app.imageSource(state.images[c.id] || c.image),c.name,'detail-art')}<div class="row wrap" style="margin-top:14px">${badge(c.species || 'human')}${badge(c.pronouns || 'adult')}${badge(`${c.age} years`)}</div><p class="muted" style="margin:17px 0 0;font-size:12px">${esc(c.appearance?.description || '')}</p></div><section><div class="eyebrow">${esc(c.role || 'Character')}</div><p class="detail-description">${esc(c.personality)}</p><h3 style="margin-top:20px">What you know</h3><p class="muted" style="font-size:12px">${esc(c.backstory || c.description || '')}</p><div class="detail-stats"><div><strong>${state.relationships[c.id] || 0}</strong><span>Relationship</span></div><div><strong>${state.memory.filter(m=>m.subject===c.id).length}</strong><span>Memories</span></div></div><form id="outfit-form" class="stack">${field('Outfit','outfit',state.outfits[c.id] || '',{options:(c.wardrobe || []).filter(o=>(state.unlockedOutfits[c.id] || []).includes(o.id)).map(o=>[o.id,o.name])})}<button class="button" type="submit">${icon('shirt')}Change outfit</button></form><div class="stack" style="margin-top:12px;gap:9px">${!state.party.includes(c.id)&&state.present.includes(c.id)&&c.recruitable!==false?button('recruit-character','Invite to your party','users'):''}${state.party.includes(c.id)?button('dismiss-character','Leave the party','users'):''}${button('character-appearance','Appearance & portrait','image')}</div></section></div>`,{wide:true,footer:button('character-memory','Character memories','heart')});
  d.on('submit','#outfit-form',async e=>{e.preventDefault();try{await app.act({kind:'outfit',characterId:c.id,value:readForm(e.target).outfit});d.close();toast('Outfit changed. Generate or select a matching portrait when ready.');}catch(err){onError(err);}});
  d.on('click','[data-action="recruit-character"]',async()=>{await app.act({kind:'recruit',characterId:c.id});d.close();});
  d.on('click','[data-action="dismiss-character"]',async()=>{await app.act({kind:'dismiss',characterId:c.id});d.close();});
  d.on('click','[data-action="character-memory"]',()=>memory(app,c.id));d.on('click','[data-action="character-appearance"]',()=>app.appearance(c));
}
export function worldMap(app){
  requireThat(app.session,'Begin or load an adventure first.');const state=app.session.save.state,compiled=app.session.compiled,from=compiled.locations.get(state.location);
  const d=modal('World map',`<p class="muted" style="font-size:12px">Travel along known connections. New places appear as your adventure unfolds.</p><div class="grid2">${[...compiled.locations.values()].filter(l=>state.discovered.includes(l.id)).map(l=>`<article class="map-location ${l.id===state.location?'current':''}"><div class="row between">${icon('pin')}${l.id===state.location?badge('You are here','warm'):state.visited.includes(l.id)?badge('Visited'):badge('Discovered')}</div><h3 style="margin-top:14px">${esc(l.name)}</h3><p>${esc(l.description || '')}</p>${button('travel-location',l.id===state.location?'Current location':'Travel here','arrow','small',`data-id="${esc(l.id)}" ${l.id===state.location||!from?.links?.includes(l.id)||!meets(state,l.requires)?'disabled':''}`)}</article>`).join('')}</div>`,{wide:true,subtitle:compiled.story.title});d.on('click','[data-action="travel-location"]',async(_e,t)=>{try{d.close();await app.act({kind:'travel',location:t.dataset.id});}catch(err){onError(err);}});
}
export function inventory(app){
  requireThat(app.session,'Begin or load an adventure first.');const save=app.session.save,s=save.state,compiled=app.session.compiled;
  const rows=Object.entries(s.inventory).filter(([,v])=>v>0);
  const d=modal('Inventory & equipment',`<div class="row wrap" style="margin-bottom:20px">${Object.entries(s.resources).map(([k,v])=>`<div class="badge warm">${icon('coin')}${v} ${esc(k)}</div>`).join('')}</div><div class="stack">${rows.map(([key,count])=>{const item=compiled.items.get(key);return `<div class="list-row"><span class="inventory-icon">${icon(item?.slot?'compass':'bag')}</span><div class="grow"><h3>${esc(item?.name || key)} ${badge('× '+count)}</h3><p>${esc(item?.description || 'An item from your adventure.')}</p>${item?.slot?`<small>Equipment slot: ${esc(item.slot)}</small>`:''}</div>${item?.slot?button('equip-item','Equip','check','small',`data-id="${esc(key)}" data-slot="${esc(item.slot)}"`):''}</div>`;}).join('') || empty('Traveling light','Items acquired in your adventure will appear here.')}</div><h3 style="margin-top:25px">Currently equipped</h3><div class="stack">${Object.entries(s.equipment).flatMap(([owner,slots])=>Object.entries(slots).map(([slot,value])=>`<div class="list-row"><div class="grow"><h3>${esc(compiled.items.get(value)?.name || value)}</h3><p>${esc(owner==='player'?save.profile.name:save.characters.find(c=>c.id===owner)?.name || owner)} · ${esc(slot)}</p></div>${button('unequip','Unequip','close','small',`data-owner="${esc(owner)}" data-slot="${esc(slot)}"`)}</div>`)).join('') || '<p class="muted" style="font-size:12px">Nothing equipped yet.</p>'}</div>`,{wide:true});
  d.on('click','[data-action="equip-item"]',(_e,t)=>{const pick=modal('Equip item',`<form id="equip-form" class="stack">${field('Give to','owner','player',{options:[['player',save.profile.name],...save.characters.filter(c=>s.present.includes(c.id)).map(c=>[c.id,c.name])]})}<small>A single item cannot be equipped by two characters at once.</small></form>`,{footer:`<button class="button primary" type="submit" form="equip-form">Equip</button>`});pick.on('submit','#equip-form',async e=>{e.preventDefault();try{await app.act({kind:'equip',characterId:readForm(e.target).owner,slot:t.dataset.slot,value:t.dataset.id});pick.close();d.close();inventory(app);}catch(err){onError(err);}});});
  d.on('click','[data-action="unequip"]',async(_e,t)=>{try{await app.act({kind:'equip',characterId:t.dataset.owner,slot:t.dataset.slot,value:''});d.close();inventory(app);}catch(err){onError(err);}});
}
export function offers(app){
  requireThat(app.session,'Begin or load an adventure first.');const compiled=app.session.compiled,state=app.session.save.state,rows=availableOffers(compiled,state).filter(o=>!o.location||o.location===state.location);
  const d=modal('Shops, jobs & services',`<div class="row between" style="margin-bottom:21px"><p class="muted" style="font-size:12px;margin:0">${esc(compiled.locations.get(state.location)?.name || '')}</p><div class="row">${Object.entries(state.resources).map(([k,v])=>badge(`${v} ${k}`,'warm')).join('')}</div></div><div class="stack">${rows.map(o=>`<div class="list-row"><span class="inventory-icon">${icon(o.kind==='job'?'compass':o.kind==='service'?'users':'bag')}</span><div class="grow"><div class="row wrap" style="margin-bottom:5px"><h3 style="margin:0">${esc(o.name)}</h3>${badge(o.kind)}</div><p>${esc(o.description || '')}</p><small>${Object.entries(o.cost || {}).length?Object.entries(o.cost).map(([k,v])=>`${v} ${esc(k)}`).join(' · '):'No cost'}${o.stock!==undefined&&o.stock>=0?` · ${Math.max(0,o.stock-(state.purchases[o.id]||0))} available`:''}</small></div>${button('take-offer',o.kind==='job'?'Take job':o.kind==='recruitment'?'Invite':'Choose','arrow','small',`data-id="${esc(o.id)}" ${!o.available?'disabled':''}`)}</div>`).join('') || empty('Nothing on offer here','Try another location. The map shows where you can travel.')}</div>`,{wide:true,subtitle:'Costs, rewards, and character state change together—or not at all.'});d.on('click','[data-action="take-offer"]',async(_e,t)=>{d.close();try{await app.act({kind:'offer',offerId:t.dataset.id});}catch(err){onError(err);}});
}
export function memory(app,subject=null){
  requireThat(app.session,'Begin or load an adventure first.');const save=app.session.save,memories=save.state.memory.filter(m=>!subject||m.subject===subject),candidates=(save.memoryCandidates || []).filter(m=>!subject||m.subject===subject);
  const label=k=>k==='world'?'World':k==='player'?save.profile.name:save.characters.find(c=>c.id===k)?.name || k;
  const d=modal(subject?`${label(subject)} · memories`:'Memories & relationships',`<div class="row wrap" style="margin-bottom:20px">${save.characters.map(c=>badge(`${c.name}: ${save.state.relationships[c.id] || 0}`,'warm')).join('')}</div>${candidates.length?`<section class="form-section" style="margin-bottom:20px"><h3>Suggested memories · review before keeping</h3><div class="stack">${candidates.map(m=>`<article class="memory-card"><small>${esc(label(m.subject))}</small><p>${esc(m.text)}</p>${m.quote?`<blockquote class="memory-quote">${esc(m.quote)}</blockquote>`:''}<div class="actions">${button('accept-memory','Keep','check','small',`data-id="${esc(m.id)}"`)}${button('reject-memory','Dismiss','close','small',`data-id="${esc(m.id)}"`)}</div></article>`).join('')}</div></section>`:''}<div class="stack">${memories.map(m=>`<article class="memory-card"><div class="row between"><small>${esc(label(m.subject))} · ${esc(m.rating)}</small>${ibutton('forget-memory','Forget this detail','trash',`data-id="${esc(m.id)}"`)}</div><p>${esc(m.text)}</p><small>Linked to the story moment that established it.</small></article>`).join('') || (candidates.length?'<p class="editor-help">No lasting facts have been kept yet. Review a suggestion above or record a detail below.</p>':empty('Room for the important details','Keep facts, promises, and shared experiences. Rewriting their source removes the associated history.'))}</div><hr><form id="memory-form" class="stack">${field('About','subject',subject || 'world',{options:[['world','World'],['player',save.profile.name],...save.characters.map(c=>[c.id,c.name])]})}${field('Remember this','text','',{type:'textarea',rows:2,required:true,extra:'maxlength="8000"'})}<button class="button" type="submit">${icon('plus')}Add memory</button></form>`,{wide:true,footer:button('suggest-memory','Find important memories','spark')});
  d.on('click','[data-action="suggest-memory"]',()=>{try{memoryAssistant(app,{onComplete:()=>{d.close();memory(app,subject);}});}catch(error){onError(error);}});
  d.on('submit','#memory-form',async e=>{e.preventDefault();try{await app.act({kind:'memory',...readForm(e.target)});d.close();memory(app,subject);}catch(err){onError(err);}});
  d.on('click','[data-action="forget-memory"]',async(_e,t)=>{await app.act({kind:'forget',memoryId:t.dataset.id});d.close();memory(app,subject);});
  const resolve=async(key,accept)=>{try{const m=app.session.save.memoryCandidates.find(c=>c.id===key);requireThat(m,'That suggestion is no longer available.');if(accept)await app.act({kind:'memory',subject:m.subject,text:m.text,rating:m.rating,sourceEvent:m.sourceEvent});await app.session.updateMetadata({memoryCandidates:app.session.save.memoryCandidates.filter(c=>c.id!==key)});d.close();memory(app,subject);}catch(err){onError(err);}};
  d.on('click','[data-action="accept-memory"]',(_e,t)=>resolve(t.dataset.id,true));d.on('click','[data-action="reject-memory"]',(_e,t)=>resolve(t.dataset.id,false));
}
